DEFINE cod_organizacion = 999;

INSERT INTO A_MNU(MNU_ORG, MNU_APL, MNU_COD, MNU_DES, MNU_ACT) (SELECT &cod_organizacion, MNU_APL, MNU_COD, MNU_DES, MNU_ACT FROM A_MNU WHERE MNU_ORG = 0); 
INSERT INTO A_MOR(MOR_ORG, MOR_APL, MOR_MNU, MOR_ELE, MOR_PRO, MOR_VIS, MOR_DES, MOR_PAD) (SELECT &cod_organizacion, MOR_APL, MOR_MNU, MOR_ELE, MOR_PRO, MOR_VIS, MOR_DES, MOR_PAD FROM A_MOR WHERE MOR_ORG = 0);
INSERT INTO A_RPG(RPG_GRU, RPG_ORG, RPG_ENT, RPG_APL, RPG_PRO, RPG_TIP) (SELECT RPG_GRU, &cod_organizacion, ENT_COD, RPG_APL, RPG_PRO, RPG_TIP FROM A_RPG JOIN A_ENT ON (&cod_organizacion = ENT_ORG) WHERE RPG_ORG = 0 AND RPG_GRU = 1);
