package es.altia.agora.business.gestionInformes;

/* Generated by Together */


import java.io.Serializable;


public class AmbitoListaValueObject implements Serializable {

    /** Construye un nuevo elemento por defecto. */
    public AmbitoListaValueObject() {
        super();
    }

    /** Construye un nuevo elemento sin identificador */

    public AmbitoListaValueObject(Integer codigo,String nome,String campo,String tipo,Integer lonxitude,Integer origen,String nomeas,Integer criterio,String descOrigen,String cri)
   {
            this.codigo = codigo;
            this.nome = nome;
            this.campo = campo;
            this.tipo = tipo;
            this.lonxitude = lonxitude;
            this.origen = origen;
            this.nomeas = nomeas;
            this.criterio = criterio;
            this.descOrigen = descOrigen;
            this.cri = cri;

            
            
    }

    /** Construye un nuevo elemento con identificador*/


    public String getDescOrigen() { return descOrigen; }
    public void setDescOrigen(String descOrigen) { this.descOrigen = descOrigen; }
    
    public Integer getCodigo() { return codigo; }
    public void setCodigo(Integer codigo) { this.codigo = codigo; }

    public String getNome() { return nome; }
    public void setNome(String nome) { this.nome = nome; }
    
    public String getCampo() { return campo; }
    public void setCampo(String campo) { this.campo = campo; }
    
    public String getTipo() { return tipo; }
    public void setTipo(String tipo) { this.tipo = tipo; }
    
    public Integer getLonxitude() { return lonxitude; }
    public void setLonxitude(Integer lonxitude) { this.lonxitude = lonxitude; }
    
    public Integer getOrigen() { return origen; }
    public void setOrigen(Integer origen) { this.origen = origen; }
    
    public String getNomeas() { return nomeas; }
    public void setNomeas(String nomeas) { this.nomeas = nomeas; }
    
    public Integer getCriterio() { return criterio; }
    public void setCriterio(Integer criterio) { this.criterio = criterio; }
    
    public String getCri() { return cri; }
    public void setCri(String cri) { this.cri = cri; }
    
    
    public String toString(){
    	String datos="";
    	datos="codigo: "+this.getCodigo();
    	return datos;	
    };


   
    private Integer codigo;
    private String nome;
    private String campo;
    private String tipo;
    private Integer lonxitude;
    private Integer origen;
    private String nomeas;
    private Integer criterio;
    private String descOrigen;
    private String cri;
    
   

}
