create or replace PROCEDURE actualizarUorsOficinasRegistro
AS 
  codInternoUorRegistro NUMBER;
BEGIN  

	codInternoUorRegistro := getUorCod('REGLAN');
	dbms_output.put_line('=========> Unidad de registro REGLAN tiene como código interno: ' || codInternoUorRegistro);
		
	UPDATE A_UOR SET UOR_PAD=codInternoUorRegistro WHERE UOR_COD_VIS='OFIC';
	UPDATE A_UOR SET UOR_NO_VIS=0 WHERE UOR_COD=codInternoUorRegistro;		
	
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFAZP';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBEA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFAMUR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFARMO';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBABU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBAUR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBIMA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBIMI';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBIRE';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBISA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBISI';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBITX';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBURB';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFBURI';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFDOAN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFDOGR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFDON2';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFDURA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFELGO';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFERAN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFERRE';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFGELU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFGETX';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFIRAN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFIRUN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFLALO';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFLAOR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFLAUD';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFMUNG';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFOION';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFONDA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPARM';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPAZP';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBAR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBAU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBEA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBIM';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBIR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBIS';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBST';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPBUR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPDOA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPDOG';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPDUR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPEIB';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPERR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPGEL';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPGET';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPIRU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPLAO';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPLAU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPMUN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPOND';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPORT';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPSAN';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPSES';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPTOL';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPVIS';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPVIX';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPZAL';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPZAR';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFPZUM';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFSAAG';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFSANT';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFSEST';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFTOLO';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFVILA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFVISM';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFVITX';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZALL';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZARA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZUMA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZAU';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZER';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZJA';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZSC';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZSM';
	UPDATE A_UOR SET OFICINA_REGISTRO=1 WHERE UOR_COD_VIS='OFZZZU';
	
	
END;
/

