CREATE TABLE [dbo].[A_AAE](
	[AAE_APL] [decimal](3, 0) NOT NULL,
	[AAE_ORG] [decimal](3, 0) NOT NULL,
	[AAE_ENT] [decimal](3, 0) NOT NULL,
	[AAE_LIC] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_AAE] PRIMARY KEY CLUSTERED 
(
	[AAE_APL] ASC,
	[AAE_ORG] ASC,
	[AAE_ENT] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_AAU](
	[AAU_APL] [decimal](3, 0) NOT NULL,
	[AAU_USU] [decimal](4, 0) NOT NULL,
	[AAU_ORG] [decimal](3, 0) NULL,
	[AAU_ENT] [decimal](3, 0) NULL,
 CONSTRAINT [PK_AAU] PRIMARY KEY CLUSTERED 
(
	[AAU_APL] ASC,
	[AAU_USU] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_AID](
	[AID_APL] [decimal](3, 0) NOT NULL,
	[AID_IDI] [decimal](1, 0) NOT NULL,
	[AID_TEX] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_AID] PRIMARY KEY CLUSTERED 
(
	[AID_APL] ASC,
	[AID_IDI] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_AML](
	[AML_COD] [decimal](3, 0) NOT NULL,
	[AML_CMP] [varchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[AML_LENG] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[AML_VALOR] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK__A_AML__2E1BDC42] PRIMARY KEY CLUSTERED 
(
	[AML_COD] ASC,
	[AML_CMP] ASC,
	[AML_LENG] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_APL](
	[APL_COD] [decimal](3, 0) NOT NULL,
	[APL_NOM] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[APL_EXE] [varchar](255) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[APL_SEG] [decimal](1, 0) NOT NULL,
	[APL_ADF] [decimal](1, 0) NOT NULL,
	[APL_DIC] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[APL_REP] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[APL_VER] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[APL_ENT] [decimal](1, 0) NOT NULL,
	[APL_EJE] [decimal](1, 0) NOT NULL,
	[APL_ICO] [varchar](255) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_APL] PRIMARY KEY CLUSTERED 
(
	[APL_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_ARE](
	[ARE_COD] [decimal](3, 0) NOT NULL,
 CONSTRAINT [PK__A_ARE__619B8048] PRIMARY KEY CLUSTERED 
(
	[ARE_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_CLS](
	[CLS_COD] [decimal](3, 0) NOT NULL,
	[CLS_ORD] [decimal](3, 0) NULL,
 CONSTRAINT [PK__A_CLS__05D8E0BE] PRIMARY KEY CLUSTERED 
(
	[CLS_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_CML](
	[CML_LENG] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[CML_CMP] [varchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[CML_COD] [decimal](3, 0) NOT NULL,
	[CML_VALOR] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_A_CML] PRIMARY KEY CLUSTERED 
(
	[CML_LENG] ASC,
	[CML_CMP] ASC,
	[CML_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_CSS](
	[CSS_COD] [decimal](3, 0) NOT NULL,
	[CSS_RUTA] [varchar](4000) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[CSS_DES] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[CSS_GENERAL] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK__A_CSS__0C85DE4D] PRIMARY KEY CLUSTERED 
(
	[CSS_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_DIRECTIVA](
	[CODIGO] [varchar](64) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[APL] [decimal](3, 0) NOT NULL,
	[ETIQ] [varchar](30) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_A_DIRECTIVA] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_EEA](
	[EEA_APL] [decimal](3, 0) NOT NULL,
	[AAE_ORG] [decimal](3, 0) NOT NULL,
	[EEA_ENT] [decimal](3, 0) NOT NULL,
	[EEA_EJE] [decimal](4, 0) NOT NULL,
	[EEA_EST] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[EEA_BDE] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_VBD] [varchar](30) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[EEA_UBD] [varchar](18) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_PWD] [varchar](18) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_DBMS] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_ARQ] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_LOG] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_TRA] [decimal](1, 0) NULL,
	[EEA_QTO] [decimal](3, 0) NULL,
	[EEA_PWDBD] [varchar](15) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_DB] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[EEA_ODBC] [text] COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_EEA] PRIMARY KEY CLUSTERED 
(
	[EEA_APL] ASC,
	[AAE_ORG] ASC,
	[EEA_ENT] ASC,
	[EEA_EJE] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_ENT](
	[ENT_ORG] [decimal](3, 0) NOT NULL,
	[ENT_COD] [decimal](3, 0) NOT NULL,
	[ENT_NOM] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[ENT_DTR] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[ENT_TIP] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_ENT] PRIMARY KEY CLUSTERED 
(
	[ENT_ORG] ASC,
	[ENT_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_GRU](
	[GRU_COD] [decimal](3, 0) NOT NULL,
	[GRU_NOM] [varchar](40) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_GRU] PRIMARY KEY CLUSTERED 
(
	[GRU_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_IDI](
	[IDI_COD] [decimal](1, 0) NOT NULL,
	[IDI_NOM] [varchar](20) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[IDI_CLAVE] [varchar](2) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_IDI] PRIMARY KEY CLUSTERED 
(
	[IDI_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_MNU](
	[MNU_ORG] [decimal](3, 0) NOT NULL,
	[MNU_APL] [decimal](3, 0) NOT NULL,
	[MNU_COD] [decimal](2, 0) NOT NULL,
	[MNU_DES] [varchar](60) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[MNU_ACT] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK_MNU] PRIMARY KEY CLUSTERED 
(
	[MNU_ORG] ASC,
	[MNU_APL] ASC,
	[MNU_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_MOR](
	[MOR_ORG] [decimal](3, 0) NOT NULL,
	[MOR_APL] [decimal](3, 0) NOT NULL,
	[MOR_MNU] [decimal](2, 0) NOT NULL,
	[MOR_ELE] [decimal](4, 0) NOT NULL,
	[MOR_PRO] [decimal](4, 0) NOT NULL,
	[MOR_VIS] [decimal](1, 0) NOT NULL,
	[MOR_DES] [varchar](80) COLLATE Modern_Spanish_CI_AS NULL,
	[MOR_PAD] [decimal](4, 0) NOT NULL,
 CONSTRAINT [PK_MOR] PRIMARY KEY CLUSTERED 
(
	[MOR_ORG] ASC,
	[MOR_APL] ASC,
	[MOR_MNU] ASC,
	[MOR_ELE] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_ORG](
	[ORG_COD] [decimal](3, 0) NOT NULL,
	[ORG_DES] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[ORG_MUN] [decimal](5, 0) NULL,
	[ORG_ICO] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[ORG_NUM] [decimal](1, 0) NULL,
	[ORG_CSS] [decimal](1, 0) NULL,
 CONSTRAINT [PK_ORG] PRIMARY KEY CLUSTERED 
(
	[ORG_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_ORGEX](
	[ORGEX_COD] [decimal](3, 0) NOT NULL,
	[ORGEX_DES] [varchar](100) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_A_ORGEX] PRIMARY KEY CLUSTERED 
(
	[ORGEX_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_OUS](
	[OUS_ORG] [decimal](3, 0) NOT NULL,
	[OUS_USU] [decimal](4, 0) NOT NULL,
 CONSTRAINT [PK_OUS] PRIMARY KEY CLUSTERED 
(
	[OUS_ORG] ASC,
	[OUS_USU] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_PID](
	[PID_APL] [decimal](3, 0) NOT NULL,
	[PID_PRO] [decimal](4, 0) NOT NULL,
	[PID_IDI] [decimal](1, 0) NOT NULL,
	[PID_DES] [varchar](80) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_PID] PRIMARY KEY CLUSTERED 
(
	[PID_APL] ASC,
	[PID_PRO] ASC,
	[PID_IDI] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_PRO](
	[PRO_APL] [decimal](3, 0) NOT NULL,
	[PRO_COD] [decimal](4, 0) NOT NULL,
	[PRO_TPR] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[PRO_FRM] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[PRO_TAC] [decimal](2, 0) NULL,
 CONSTRAINT [PK_PRO] PRIMARY KEY CLUSTERED 
(
	[PRO_APL] ASC,
	[PRO_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_RPG](
	[RPG_GRU] [decimal](3, 0) NOT NULL,
	[RPG_ORG] [decimal](3, 0) NOT NULL,
	[RPG_ENT] [decimal](3, 0) NOT NULL,
	[RPG_APL] [decimal](3, 0) NOT NULL,
	[RPG_PRO] [decimal](4, 0) NOT NULL,
	[RPG_TIP] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK_RPG] PRIMARY KEY CLUSTERED 
(
	[RPG_GRU] ASC,
	[RPG_ORG] ASC,
	[RPG_ENT] ASC,
	[RPG_APL] ASC,
	[RPG_PRO] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_RPU](
	[RPU_USU] [decimal](4, 0) NOT NULL,
	[RPU_ORG] [decimal](3, 0) NOT NULL,
	[RPU_ENT] [decimal](3, 0) NOT NULL,
	[RPU_APL] [decimal](3, 0) NOT NULL,
	[RPU_PRO] [decimal](4, 0) NOT NULL,
	[RPU_TIP] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK_RPU] PRIMARY KEY CLUSTERED 
(
	[RPU_USU] ASC,
	[RPU_ORG] ASC,
	[RPU_ENT] ASC,
	[RPU_APL] ASC,
	[RPU_PRO] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_TEX](
	[TEX_APL] [decimal](3, 0) NOT NULL,
	[TEX_COD] [varchar](30) COLLATE Modern_Spanish_CS_AS NOT NULL,
	[TEX_IDI] [decimal](1, 0) NOT NULL,
	[TEX_DES] [varchar](255) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[TEX_USO] [decimal](1, 0) NULL,
	[TEX_FEC] [datetime] NULL,
 CONSTRAINT [PK_TEX] PRIMARY KEY CLUSTERED 
(
	[TEX_APL] ASC,
	[TEX_COD] ASC,
	[TEX_IDI] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_TPML](
	[TPML_COD] [decimal](2, 0) NOT NULL,
	[TPML_CMP] [varchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[TPML_LENG] [varchar](1) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[TPML_VALOR] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK__A_TPML__5DCAEF64] PRIMARY KEY CLUSTERED 
(
	[TPML_COD] ASC,
	[TPML_CMP] ASC,
	[TPML_LENG] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_TPR](
	[TPR_COD] [decimal](2, 0) NOT NULL,
 CONSTRAINT [PK__A_TPR__08B54D69] PRIMARY KEY CLUSTERED 
(
	[TPR_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_UAE](
	[UAE_USU] [decimal](4, 0) NOT NULL,
	[UAE_ORG] [decimal](3, 0) NOT NULL,
	[UAE_ENT] [decimal](3, 0) NOT NULL,
	[UAE_APL] [decimal](3, 0) NOT NULL,
	[UAE_EDE] [decimal](4, 0) NULL,
 CONSTRAINT [PK_UAE] PRIMARY KEY CLUSTERED 
(
	[UAE_USU] ASC,
	[UAE_ORG] ASC,
	[UAE_ENT] ASC,
	[UAE_APL] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_UGO](
	[UGO_USU] [decimal](4, 0) NOT NULL,
	[UGO_ORG] [decimal](3, 0) NOT NULL,
	[UGO_ENT] [decimal](3, 0) NOT NULL,
	[UGO_GRU] [decimal](3, 0) NOT NULL,
	[UGO_APL] [decimal](3, 0) NOT NULL,
 CONSTRAINT [PK_UGO] PRIMARY KEY CLUSTERED 
(
	[UGO_USU] ASC,
	[UGO_ORG] ASC,
	[UGO_ENT] ASC,
	[UGO_GRU] ASC,
	[UGO_APL] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_UOREX](
	[UOREX_COD] [decimal](3, 0) NOT NULL,
	[UOREX_ORG] [decimal](3, 0) NOT NULL,
	[UOREX_NOM] [varchar](100) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_A_UOREX] PRIMARY KEY CLUSTERED 
(
	[UOREX_COD] ASC,
	[UOREX_ORG] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_UOU](
	[UOU_ORG] [decimal](3, 0) NOT NULL,
	[UOU_ENT] [decimal](3, 0) NOT NULL,
	[UOU_UOR] [decimal](5, 0) NOT NULL,
	[UOU_USU] [decimal](4, 0) NOT NULL,
	[UOU_CAR] [decimal](3, 0) NULL,
 CONSTRAINT [PK_UOU] PRIMARY KEY CLUSTERED 
(
	[UOU_ORG] ASC,
	[UOU_ENT] ASC,
	[UOU_UOR] ASC,
	[UOU_USU] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[A_USU](
	[USU_COD] [decimal](4, 0) NOT NULL,
	[USU_IDI] [decimal](1, 0) NOT NULL,
	[USU_APL] [decimal](3, 0) NULL,
	[USU_LOG] [varchar](255) COLLATE Modern_Spanish_CS_AS NOT NULL,
	[USU_PAS] [varchar](40) COLLATE Modern_Spanish_CS_AS NOT NULL,
	[USU_NOM] [varchar](40) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[USU_ACT] [decimal](1, 0) NOT NULL,
	[USU_CON] [decimal](1, 0) NOT NULL,
	[USU_LIS] [decimal](1, 0) NOT NULL,
	[USU_TEB] [decimal](1, 0) NOT NULL,
	[USU_TDM] [decimal](1, 0) NOT NULL,
	[USU_ICO] [decimal](1, 0) NOT NULL,
	[USU_MPR] [decimal](1, 0) NOT NULL,
	[USU_FBA] [datetime] NULL,
	[USU_IGS] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_IGN] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_IPS] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_IPN] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_CBQ] [decimal](15, 0) NULL,
	[USU_ICB] [varchar](255) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_NIF] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_FIRMANTE] [decimal](1, 0) NULL,
	[USU_EMAIL] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_FIRMA] [image] NULL,
	[USU_TIPO_FIRMA] [varchar](25) COLLATE Modern_Spanish_CI_AS NULL,
	[USU_BLQ] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK_USU] PRIMARY KEY CLUSTERED 
(
	[USU_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE A_USU_ROTACION_PASS
(
 COD_PASS DECIMAL(4, 0) NOT NULL,
 USU_PASS VARCHAR(40) COLLATE Modern_Spanish_CS_AS NOT NULL, 
 FEC_ALTA datetime,   
 USU_COD DECIMAL(4,0) NOT NULL,
 PRIMARY KEY(COD_PASS),
 FOREIGN KEY ([USU_COD])
 REFERENCES [dbo].[A_USU] ([USU_COD]))
 GO

CREATE TABLE [dbo].[A_USU_DIR](
	[DIR] [varchar](64) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[USU] [decimal](4, 0) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_AUT](
	[AUT_PAI] [decimal](3, 0) NOT NULL,
	[AUT_COD] [decimal](2, 0) NOT NULL,
	[AUT_NOM] [varchar](25) COLLATE Modern_Spanish_CI_AS NULL,
	[AUT_NOL] [varchar](50) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_T_AUT] PRIMARY KEY CLUSTERED 
(
	[AUT_PAI] ASC,
	[AUT_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_ESC](
	[ESC_COD] [varchar](2) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[ESC_DES] [varchar](60) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_T_ESC] PRIMARY KEY CLUSTERED 
(
	[ESC_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_MUN](
	[MUN_PAI] [decimal](3, 0) NOT NULL,
	[MUN_PRV] [decimal](2, 0) NOT NULL,
	[MUN_COD] [decimal](4, 0) NOT NULL,
	[MUN_PJU] [decimal](2, 0) NULL,
	[MUN_COM] [decimal](5, 0) NULL,
	[MUN_NOM] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[MUN_NOL] [varchar](50) COLLATE Modern_Spanish_CI_AS NULL,
	[MUN_DCO] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[MUN_SUP] [decimal](9, 2) NULL,
	[MUN_ALT] [decimal](5, 0) NULL,
	[MUN_KMC] [decimal](4, 0) NULL,
	[MUN_LTN] [decimal](5, 2) NULL,
	[MUN_LTS] [decimal](5, 2) NULL,
	[MUN_LES] [decimal](5, 2) NULL,
	[MUN_LOE] [decimal](5, 2) NULL,
	[MUN_SIT] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_T_MUN] PRIMARY KEY CLUSTERED 
(
	[MUN_PAI] ASC,
	[MUN_PRV] ASC,
	[MUN_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_PAI](
	[PAI_COD] [decimal](3, 0) NOT NULL,
	[PAI_NOM] [varchar](25) COLLATE Modern_Spanish_CI_AS NULL,
	[PAI_NOL] [varchar](50) COLLATE Modern_Spanish_CI_AS NULL,
	[PAI_DCO] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_T_PAI] PRIMARY KEY CLUSTERED 
(
	[PAI_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_PJU](
	[PJU_PAI] [decimal](3, 0) NOT NULL,
	[PJU_PRV] [decimal](2, 0) NOT NULL,
	[PJU_COD] [decimal](2, 0) NOT NULL,
	[PJU_NOM] [varchar](25) COLLATE Modern_Spanish_CI_AS NULL,
	[PJU_NOL] [varchar](50) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_T_PJU] PRIMARY KEY CLUSTERED 
(
	[PJU_PAI] ASC,
	[PJU_PRV] ASC,
	[PJU_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_PLT](
	[PLT_COD] [varchar](3) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[PLT_DES] [varchar](60) COLLATE Modern_Spanish_CI_AS NOT NULL,
 CONSTRAINT [PK_T_PLT] PRIMARY KEY CLUSTERED 
(
	[PLT_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[T_PRV](
	[PRV_PAI] [decimal](3, 0) NOT NULL,
	[PRV_COD] [decimal](2, 0) NOT NULL,
	[PRV_AUT] [decimal](2, 0) NULL,
	[PRV_NOM] [varchar](25) COLLATE Modern_Spanish_CI_AS NULL,
	[PRV_NOL] [varchar](50) COLLATE Modern_Spanish_CI_AS NULL,
 CONSTRAINT [PK_T_PRV] PRIMARY KEY CLUSTERED 
(
	[PRV_PAI] ASC,
	[PRV_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USU_FIR_DEL](
	[USU_COD] [decimal](4, 0) NOT NULL,
	[USU_DELEGADO] [decimal](4, 0) NOT NULL,
	[FX_DESDE] [datetime] NOT NULL,
	[FX_HASTA] [datetime] NOT NULL,
	[PVERSION] [decimal](38, 0) NOT NULL,
 CONSTRAINT [USU_FIR_DEL_PK] PRIMARY KEY CLUSTERED 
(
	[USU_COD] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE USUARIO_PROC_RESTRINGIDO(
	PRO_COD VARCHAR(5) NOT NULL,	
	USU_COD DECIMAL(4,0) NOT NULL,  
	ORG_COD DECIMAL(3,0) NOT NULL,	
	ENT_COD DECIMAL(3,0) NOT NULL,	
	CONSTRAINT FK_FUSUARIO_PRO_USU_COD FOREIGN KEY (USU_COD)
		REFERENCES A_USU(USU_COD) ON DELETE CASCADE,
	CONSTRAINT FK_FUSUARIO_PRO_ORG_COD FOREIGN KEY (ORG_COD)
		REFERENCES A_ORG(ORG_COD) ON DELETE CASCADE,			
	PRIMARY KEY(PRO_COD,USU_COD,ORG_COD,ENT_COD))
GO	


-- Creación de claves foráneas
ALTER TABLE [dbo].[A_AAE] ADD  
FOREIGN KEY ([AAE_ORG], [AAE_ENT])
REFERENCES [dbo].[A_ENT] ( [ENT_ORG], [ENT_COD] )
GO
ALTER TABLE [dbo].[A_AAE] ADD  
FOREIGN KEY ([AAE_APL])
REFERENCES [dbo].[A_APL] ( APL_COD )
GO

ALTER TABLE [dbo].[A_AAU] ADD  
FOREIGN KEY ([AAU_APL])
REFERENCES [dbo].[A_APL] ( APL_COD )
GO
ALTER TABLE [dbo].[A_AAU] ADD  
FOREIGN KEY ([AAU_USU])
REFERENCES [dbo].[A_USU] ( USU_COD )
GO
ALTER TABLE [dbo].[A_AAU] ADD  
FOREIGN KEY ([AAU_ORG],[AAU_ENT])
REFERENCES [dbo].[A_ENT] ( [ENT_ORG],[ENT_COD] )
GO

---------
ALTER TABLE [dbo].[A_AID] ADD
FOREIGN KEY ([AID_APL])
REFERENCES [dbo].[A_APL] ( [APL_COD] )
GO
ALTER TABLE [dbo].[A_AID]
ADD  CONSTRAINT [FK_AID_REL_IDI_A_IDI]
FOREIGN KEY ([AID_IDI])
REFERENCES [dbo].[A_IDI] ( [IDI_COD] )
GO

ALTER TABLE [dbo].[A_AML] ADD 
FOREIGN KEY ([AML_COD])
REFERENCES [dbo].[A_ARE] ( [ARE_COD] )
GO

ALTER TABLE [dbo].[A_CML]
ADD  FOREIGN KEY ([CML_COD])
REFERENCES [dbo].[A_CLS] ( [CLS_COD] )
GO

ALTER TABLE [dbo].[A_EEA]
ADD  FOREIGN KEY ([EEA_APL], [AAE_ORG], [EEA_ENT])
REFERENCES [dbo].[A_AAE] ( [AAE_APL], [AAE_ORG], [AAE_ENT] )
GO

ALTER TABLE [dbo].[A_ENT]
ADD  FOREIGN KEY ([ENT_ORG])
REFERENCES [dbo].[A_ORG] ( [ORG_COD] )
GO

ALTER TABLE [dbo].[A_MNU]
ADD  FOREIGN KEY ([MNU_APL])
REFERENCES [dbo].[A_APL] ( [APL_COD] )
GO
ALTER TABLE [dbo].[A_MNU]
ADD  FOREIGN KEY ([MNU_ORG])
REFERENCES [dbo].[A_ORG] ( [ORG_COD] )
GO

ALTER TABLE [dbo].[A_MOR]
ADD  FOREIGN KEY ([MOR_ORG], [MOR_APL], [MOR_MNU])
REFERENCES [dbo].[A_MNU] ( [MNU_ORG], [MNU_APL], [MNU_COD] )
GO

ALTER TABLE [dbo].[A_OUS]
ADD  FOREIGN KEY ([OUS_ORG])
REFERENCES [dbo].[A_ORG] ( [ORG_COD] )
GO
ALTER TABLE [dbo].[A_OUS]
ADD  FOREIGN KEY ([OUS_USU])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO

ALTER TABLE [dbo].[A_PID]
ADD  FOREIGN KEY ([PID_IDI])
REFERENCES [dbo].[A_IDI] ( [IDI_COD] )
GO
ALTER TABLE [dbo].[A_PID]
ADD  FOREIGN KEY ([PID_APL], [PID_PRO])
REFERENCES [dbo].[A_PRO] ( [PRO_APL], [PRO_COD] )
GO

ALTER TABLE [dbo].[A_PRO]
ADD  FOREIGN KEY ([PRO_APL])
REFERENCES [dbo].[A_APL] ( [APL_COD] )
GO

ALTER TABLE [dbo].[A_RPG]
ADD  FOREIGN KEY ([RPG_ORG], [RPG_ENT])
REFERENCES [dbo].[A_ENT] ( [ENT_ORG], [ENT_COD] )
GO
ALTER TABLE [dbo].[A_RPG]
ADD  FOREIGN KEY ([RPG_GRU])
REFERENCES [dbo].[A_GRU] ( [GRU_COD] )
GO
ALTER TABLE [dbo].[A_RPG]
ADD  FOREIGN KEY ([RPG_APL], [RPG_PRO])
REFERENCES [dbo].[A_PRO] ( [PRO_APL], [PRO_COD] )
GO

ALTER TABLE [dbo].[A_RPU]
ADD  FOREIGN KEY ([RPU_APL], [RPU_PRO])
REFERENCES [dbo].[A_PRO] ( [PRO_APL], [PRO_COD] )
GO
ALTER TABLE [dbo].[A_RPU]
ADD  FOREIGN KEY ([RPU_ORG], [RPU_ENT])
REFERENCES [dbo].[A_ENT] ( [ENT_ORG], [ENT_COD] )
GO
ALTER TABLE [dbo].[A_RPU]
ADD  FOREIGN KEY ([RPU_USU])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO

ALTER TABLE [dbo].[A_TEX]
ADD  FOREIGN KEY ([TEX_APL])
REFERENCES [dbo].[A_APL] ( [APL_COD] )
GO
ALTER TABLE [dbo].[A_TEX]
ADD  FOREIGN KEY ([TEX_IDI])
REFERENCES [dbo].[A_IDI] ( [IDI_COD] )
GO

ALTER TABLE [dbo].[A_TPML]
ADD  FOREIGN KEY ([TPML_COD])
REFERENCES [dbo].[A_TPR] ( [TPR_COD] )
GO

ALTER TABLE [dbo].[A_UAE]
ADD  FOREIGN KEY ([UAE_USU])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO
ALTER TABLE [dbo].[A_UAE]
ADD  FOREIGN KEY ([UAE_APL], [UAE_ORG], [UAE_ENT])
REFERENCES [dbo].[A_AAE] ( [AAE_APL], [AAE_ORG], [AAE_ENT] )
GO

ALTER TABLE [dbo].[A_UGO]
ADD  FOREIGN KEY ([UGO_USU])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO
ALTER TABLE [dbo].[A_UGO]
ADD  FOREIGN KEY ([UGO_GRU])
REFERENCES [dbo].[A_GRU] ( [GRU_COD] )
GO
ALTER TABLE [dbo].[A_UGO]
ADD  FOREIGN KEY ([UGO_ORG])
REFERENCES [dbo].[A_ORG] ( [ORG_COD] )
GO
ALTER TABLE [dbo].[A_UGO]
ADD  FOREIGN KEY ([UGO_ORG], [UGO_ENT])
REFERENCES [dbo].[A_ENT] ( [ENT_ORG], [ENT_COD] )
GO

ALTER TABLE [dbo].[A_UOU]
ADD  FOREIGN KEY ([UOU_USU])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO

ALTER TABLE [dbo].[A_USU]
ADD  FOREIGN KEY ([USU_IDI])
REFERENCES [dbo].[A_IDI] ( [IDI_COD] )
GO
ALTER TABLE [dbo].[A_USU]
ADD  FOREIGN KEY ([USU_APL])
REFERENCES [dbo].[A_APL] ( [APL_COD] )
GO

ALTER TABLE [dbo].[T_AUT]
ADD  FOREIGN KEY ([AUT_PAI])
REFERENCES [dbo].[T_PAI] ( [PAI_COD] )
GO

ALTER TABLE [dbo].[T_MUN]
ADD  FOREIGN KEY ([MUN_PAI], [MUN_PRV], [MUN_PJU])
REFERENCES [dbo].[T_PJU] ( [PJU_PAI], [PJU_PRV], [PJU_COD] )
GO
ALTER TABLE [dbo].[T_MUN]
ADD  FOREIGN KEY ([MUN_PAI], [MUN_PRV])
REFERENCES [dbo].[T_PRV] ( [PRV_PAI], [PRV_COD] )
GO

ALTER TABLE [dbo].[T_PJU]
ADD  FOREIGN KEY ([PJU_PAI], [PJU_PRV])
REFERENCES [dbo].[T_PRV] ( [PRV_PAI], [PRV_COD] )
GO

ALTER TABLE [dbo].[T_PRV]
ADD  FOREIGN KEY ([PRV_PAI])
REFERENCES [dbo].[T_PAI] ( [PAI_COD] )
GO
ALTER TABLE [dbo].[T_PRV]
ADD  FOREIGN KEY ([PRV_PAI], [PRV_AUT])
REFERENCES [dbo].[T_AUT] ( [AUT_PAI], [AUT_COD] )
GO

ALTER TABLE [dbo].[USU_FIR_DEL]
ADD  FOREIGN KEY ([USU_DELEGADO])
REFERENCES [dbo].[A_USU] ( [USU_COD] )
GO


-- Creación de índices

CREATE INDEX REL_ORG_ENT_FK ON A_ENT (ENT_ORG);
CREATE INDEX REL_ENT_AAE_FK ON A_AAE (AAE_ORG, AAE_ENT);
CREATE INDEX REL_APL_AAE_FK ON A_AAE (AAE_APL);
CREATE INDEX REL_IDI_USU_FK ON A_USU (USU_IDI);
CREATE INDEX REL_APL_USU_FK ON A_USU (USU_APL);
CREATE INDEX REL_USU_AAU_FK ON A_AAU (AAU_USU)  ;
CREATE INDEX REL_APL_AAU_FK ON A_AAU (AAU_APL);
CREATE INDEX REL_ENT_AAU_FK ON A_AAU (AAU_ORG, AAU_ENT) ;
CREATE INDEX REL_APL_AID_FK ON A_AID (AID_APL);
CREATE INDEX REL_IDI_AID_FK ON A_AID (AID_IDI);
CREATE INDEX REL_AAE_EEA_FK ON  A_EEA (AAE_ORG, EEA_ENT, EEA_APL);
CREATE INDEX REL_ORG_MNU_FK ON A_MNU (MNU_ORG);
CREATE INDEX REL_APL_MNU_FK ON A_MNU (MNU_APL);
CREATE INDEX REL_MNU_MOR_FK ON A_MOR (MOR_ORG, MOR_APL, MOR_MNU);
CREATE INDEX REL_PRO_MOR_FK ON A_MOR (MOR_PRO);
CREATE INDEX REL_ORG_OUS_FK ON A_OUS (OUS_ORG);
CREATE INDEX REL_USU_OUS_FK ON A_OUS (OUS_USU);
CREATE INDEX REL_APL_PRO_FK ON A_PRO (PRO_APL);
CREATE INDEX REL_PRO_PID_FK ON A_PID (PID_APL, PID_PRO) ;
CREATE INDEX REL_IDI_PID_FK ON A_PID (PID_IDI);
CREATE INDEX REL_PRO_RPG_FK ON A_RPG (RPG_APL, RPG_PRO);
CREATE INDEX REL_GRU_RPG_FK ON A_RPG (RPG_GRU);
CREATE INDEX REL_ENT_RPG_FK ON A_RPG (RPG_ORG, RPG_ENT);
CREATE INDEX REL_RPO_RPU_FK ON A_RPU (RPU_APL, RPU_PRO);
CREATE INDEX REL_USU_RPU_FK ON A_RPU (RPU_USU);
CREATE INDEX REL_ENT_RPU_FK ON A_RPU (RPU_ORG, RPU_ENT);
CREATE INDEX REL_APL_TEX_FK ON A_TEX (TEX_APL);
CREATE INDEX REL_IDI_TEX_FK ON A_TEX (TEX_IDI);
CREATE INDEX REL_USU_UAE_FK ON A_UAE (UAE_USU);
CREATE INDEX REL_AAE_UAE_FK ON A_UAE (UAE_ORG, UAE_ENT, UAE_APL);
CREATE INDEX REL_GRU_UGO_FK ON A_UGO (UGO_GRU);
CREATE INDEX REL_ENT_UGO_FK ON A_UGO (UGO_ORG, UGO_ENT);
CREATE INDEX REL_APL_UGO_FK ON A_UGO (UGO_APL);
CREATE INDEX REL_USU_UGO_FK ON A_UGO (UGO_USU);
CREATE INDEX REL_T_39_FK ON T_AUT (AUT_PAI);
CREATE INDEX REL_T_40_FK ON T_PRV (PRV_PAI);
CREATE INDEX REL_T_41_FK ON T_PRV (PRV_PAI, PRV_AUT);
CREATE INDEX REL_T_44_FK ON T_PJU (PJU_PAI, PJU_PRV);
CREATE INDEX REL_T_46_FK ON T_MUN (MUN_PAI, MUN_PRV, MUN_PJU);
CREATE INDEX REL_T_42_FK ON T_MUN (MUN_COM);
CREATE INDEX REL_T_47_FK ON T_MUN (MUN_PAI, MUN_PRV);
GO

