INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (3,55,2,'Parámetros por defecto');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,58,2,'Consulta Xeral');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,59,2,'Consulta Expedientes')
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,60,2,'Consulta Campos Sup.');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,61,2,'Exp. pendientes');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,62,2,'Buzón de entrada');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,63,2,'Xestión de incidencias');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,64,2,'Reabrir expediente');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,65,2,'Consulta');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,66,2,'Informes');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,67,2,'Informes de Exped.');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,68,2,'Xeración de informes');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,69,2,'Buzón de informes');

INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (15,4,2,'Xestión de formularios');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (15,5,2,'Mantemento formularios');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (15,6,2,'Tipos de formularios');
INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (15,7,2,'Estados de formularios');

INSERT INTO A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (18,1,2,'Usuarios de formularios');


Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,1,2,'Rexistro de Entrada');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,2,2,'Rexistro de Saída');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,3,2,'Mantementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,4,2,'Buzón');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,12,2,'Mant. de Entradas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,13,2,'Reservas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,15,2,'Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,16,2,'Peche del Registro');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,17,2,'Dilixencias Diarias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,22,2,'Mant. de Saídas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,23,2,'Reservas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,25,2,'Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,26,2,'Pche del Registro');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,27,2,'Dilixencias Diarias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,31,2,'Temas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,32,2,'Actuacións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,33,2,'Tipos de Documento');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,34,2,'Tipos de Remitente');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,35,2,'Tipos de Transporte');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,131,2,'Reserva Número Orde');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,132,2,'Consulta de Reservas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,151,2,'Impresión Libro Rex.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,152,2,'Rel. Unidad Tramit.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,153,2,'Dilixencias Diarias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,231,2,'Reserva Número Orde');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,232,2,'Consulta de Reservas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,251,2,'Impresión Libro Rex.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,252,2,'Rel. Unidade Orgánica');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,253,2,'Dilixencias Diarias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,255,2,'Apertura do Rexistro');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,256,2,'Apertura do Rexistro');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,257,2,'Gener. Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,259,2,'Entr. Rexeitadas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,260,2,'Cargas masivas de rexistros');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,261,2,'Mantemento de Roles');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (1,265,2,'Asuntos');
INSERT INTO A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (1,269, 1, 'Rel. Des. outra administración');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,1,2,'Terceiros e Domicilios');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,2,2,'Mantementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,4,2,'Territorio');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,24,2,'Tramos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,26,2,'Distritos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,27,2,'Códigos Postais');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,29,2,'Entidades Colectivas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,30,2,'Entidades Singulares');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,31,2,'Nucleos Diseminados');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,40,2,'Modif. Viais');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,41,2,'Fusión/División');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,42,2,'Viais');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,44,2,'Seccións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,51,2,'Xestión Terceiros');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,52,2,'Depurar Vías');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (3,53,2,'Depurar Terceros');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,1,2,'Procedementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,3,2,'Informes de Xestión');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,11,2,'Def. Procedementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,12,2,'Catálogo');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,47,2,'Relacións Pendientes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,48,2,'Crear Relación');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,49,2,'Desfacer Relación');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (4,50,2,'Relacións');
INSERT INTO A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) VALUES (4,57,2,'Exp. pendentes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,1,2,'Mant. Básicos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,2,2,'Seguridade');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,10,2,'Organizacións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,11,2,'Entidades');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,13,2,'Áreas o Clasif.Proced.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,14,2,'Clasificación de Trámites');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,15,2,'Etiquetas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,16,2,'Aplicacións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,17,2,'Tipo de Procedementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,18,2,'Idiomas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,19,2,'Textos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,20,2,'Usuarios');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,22,2,'Procesos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,23,2,'Menús');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,24,2,'Aplicacións-Entidades');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,33,2,'Unidades Tramitadoras');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,35,2,'Mant. Ent. Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,36,2,'Mant. Entidades');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,37,2,'Mant. Estructuras');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,38,2,'Paises');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,39,2,'Provincias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,40,2,'Municipios');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,41,2,'Numeracións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,43,2,'Usos Vivenda');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,45,2,'Plantas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,46,2,'Escaleiras');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,49,2,'Autonomias');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,50,2,'Usuario-Menús');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,51,2,'Unid. Reg. Externas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,52,2,'Org. Externas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,53,2,'Mant. Padrón');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,54,2,'Titulacións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,55,2,'Tipos de Operacións');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,56,2,'Tipos de Intercambios');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,57,2,'Tipos de Certificados');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,58,2,'Causas de Certificado  ');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (5,61,2,'Estilos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (7,1,2,'Mantementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (7,11,2,'Oficinas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (7,12,2,'Unidades');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (7,13,2,'Procedementos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,0,2,'Mant. Básicos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,1,2,'Seguridade');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,2,2,'Conf. del Sistema');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,4,2,'Departamentos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,5,2,'Unidades Orgánicas');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,6,2,'Relación UOR-UTR');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,7,2,'Usuarios-Menús');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,8,2,'Calendario');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,11,2,'Usuarios');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,12,2,'Cargos Expediente');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,13,2,'Cargos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,14,2,'Campos despregables');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,15,2,'Asuntos Rexistro');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,17,2,'Estilos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (9,21,2,'Configuración de listados');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (11,0,2,'PORTAFIRMAS');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (11,1,2,'Delegación Firma');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (11,2,2,'Busca Documentos');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (16,0,2,'Xestión de Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (16,1,2,'Solicitudes de Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (16,2,2,'Xeneración de Informes');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values (16,3,2,'Buzón de Informes');

insert into A_PID(PID_APL,PID_PRO,PID_IDI,PID_DES) values (20,0,2,'CONVERSOR XPDL');
GO

Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (3,2,'TERCEIROS E TERRITORIO');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (4,2,'XESTIÓN DE EXPEDIENTES');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (5,2,'ADMINISTRADOR XERAL');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (6,2,'DOCUMENTOS');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (9,2,'ADMINISTRADOR LOCAL');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (10,2,'INFORMES DE DIRECCIÓN');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (11,2,'PORTAFIRMAS');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (15,2,'XESTIÓN DE FORMULARIOS');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (16,2,'XESTIÓN DE INFORMES');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (17,2,'INTEGRACION DE SERVICIOS WEB');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (18,2,'USUARIOS DE FORMULARIOS');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (98,2,'INFORME ESTADÍSTICAS DE REXISTRO');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (20,2,'CONVERSOR XPDL');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (1,2,'REXISTRO DE ENTRADA/SAÍDA');
GO
