Insert into A_IDI (IDI_COD,IDI_NOM,IDI_CLAVE) values (4,'Euskera','EU');
GO

Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (1,4,'SARRERA/IRTEERA ERREGISTROA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (3,4,'HIRUGARRENAK ETA LURRALDEA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (4,4,'ESPEDIENTEEN KUDEAKETA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (5,4,'ADMINISTRATZAILE OROKORRA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (6,4,'DOKUMENTUAK');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (9,4,'ADMINISTRATZAILE LOKALA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (10,4,'ZUZENDARITZA TXOSTENAK');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (11,4,'SINADURA ZORROA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (15,4,'FORMULARIOAK KUDEATZEA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (16,4,'TXOSTENAK KUDEATZEA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (17,4,'WEB ZERBITZUEN INTEGRAZIOA');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (18,4,'FORMULARIO ERABILTZAILEAK');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (19,4,'ERABILTZAILE PARAMETROAK');
Insert into A_AID (AID_APL,AID_IDI,AID_TEX) values (98,4,'ERREGISTRO ESTATISTIKEN TXOSTENA');
GO

Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,261,4,'Rolak mantentzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,265,4,'Gaiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,55,4,'Lehenetsitako parametroak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,57,4,'Izapidetzeke dauden esped.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,58,4,'Kontsulta orokorra');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,59,4,'Espedienteen kontsulta');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,60,4,'Gehig. erem. konts.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,61,4,'Kontsulta');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,62,4,'Txostenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,65,4,'Txosten-postontzia');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,12,4,'Sarrerak mantentzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,13,4,'Erreserbak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,15,4,'Txostenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,27,4,'Eguneko eginbideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,23,4,'Erreserbak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,33,4,'Dokumentu motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,34,4,'Igorle motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,1,4,'Sarrera-erregistroa');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,2,4,'Irteera-erregistroa');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,4,3,'Mantentzeak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,153,4,'Eguneko eginbideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,16,4,'Erregistroa ixtea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,17,4,'Eguneko eginbideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,257,4,'Txostenak sortzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,22,4,'Irteerak mantentzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,26,4,'Erregistroa ixtea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,256,4,'Erregistroa irekitzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,32,4,'Jardunak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,131,4,'Agindu-zenbakiaren erreserba');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,151,4,'Erregistro-liburua inprimatzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,152,4,'Izapidetze-unitateen zerr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,258,4,'Herritarraren webgunea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,231,4,'Agindu-zenbakiaren erreserba');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,251,4,'Erregistro-liburua inprimatzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,252,4,'Unitate organikoen zerr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,253,4,'Eguneko eginbideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,255,4,'Erregistroa irekitzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,4,4,'Postontzia');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,259,4,'Baztertutako sarr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,35,4,'Garraio mota');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,232,4,'Erreserba-kontsulta');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,25,4,'Txostenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,31,4,'Gaiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,132,4,'Erreserba-kontsulta');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(1,260,4,'Erregistro-karga masiboak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,4,4,'Lurraldea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,40,4,'Bideak aldatzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,51,4,'Hirugarrenen kudeaketa');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,52,4,'Araztu bideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,53,4,'Araztu hirugarrenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,41,4,'Bat egitea/Banantzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,42,4,'Bideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,24,4,'Tarteak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,26,4,'Barrutiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,27,4,'Posta-kodeak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,29,4,'Erakunde kolektiboak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,30,4,'Banako erakundeak ');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,31,4,'Nukleo barreiatuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,44,4,'Atalak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,1,4,'Hirugarrenak eta helbideak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(3,2,4,'Mantentzeak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,47,4,'Izapidetzeke dauden zerr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,48,4,'Sortu erlazio-zerr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,4,3,'Kudeaketa-txostenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,16,4,'Sarrera-postontzia');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,18,4,'Espedienteen kontsulta');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,20,4,'Gehigarrien er.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,21,4,'Gertakarien kudeaketa');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,1,4,'Prozedurak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,64,4,'Txostenak sortzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,22,4,'Berriz ireki espedientea ');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,19,4,'Orokorren er.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,11,4,'Prozeduren def.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,63,4,'Espediente-txostenak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,12,4,'Katalogoa');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,15,4,'Izapidetzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,17,4,'Izapidetzeke dauden esp.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,49,4,'Desegin erlazio-zerr.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(4,50,4,'Erlazio-zerrk.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,20,4,'Erabiltzaileak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,53,4,'Errolda mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,2,4,'Segurtasuna');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,10,4,'Erakundeak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,11,4,'Entitateak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,33,4,'Izapidetze-unitateak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,15,4,'Etiketak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,16,4,'Aplikazioak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,18,4,'Hizkuntzak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,22,4,'Prozesuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,23,4,'Menuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,1,4,'Oinarrizko mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,36,4,'Erakundeak mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,51,4,'Kanpoko erreg. unit.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,37,4,'Egiturak mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,52,4,'Kanpoko erak.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,35,4,'Txostenen ent. mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,40,4,'Udalerriak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,14,4,'Izapideen sailkapena');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,17,4,'Prozedura motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,38,4,'Herrialdeak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,39,4,'Probintziak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,41,4,'Zenbakiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,43,4,'Etxebizitza-erabilerak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,45,4,'Solairuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,62,4,'Dokumentu motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,46,4,'Eskailerak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,24,4,'Aplikazioak-Entitateak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,61,4,'Estiloak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,13,4,'Arloak edo Prozed. Sailk.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,49,4,'Autonomiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,50,4,'Erabiltzailea-Menuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,54,4,'Titulazioak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,55,4,'Eragiketa motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,56,4,'Truke motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,57,4,'Ziurtagiri motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,58,4,'Ziurtagiri-kausak  ');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(5,19,4,'Testuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,2,4,'Sistemaren konf.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,0,4,'Oinarrizko mant.');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,4,4,'Departamentuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,5,4,'Unitate organikoak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,13,4,'Karguak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,18,4,'Zerrendatuak konfiguratzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,17,4,'Estiloak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,12,4,'Espedienteko karguak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,14,4,'Goitibeherako eremuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,15,4,'Erregistroko gaiak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,6,4,'UOR-IZU erlazio-zerrenda');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,8,4,'Egutegia');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,7,4,'Erabiltzaileak-Menuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,11,4,'Erabiltzaileak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(9,1,4,'Segurtasuna');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(11,0,4,'SINADURA ZORROA');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(11,2,4,'Bilatu dokumentuak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(11,1,4,'Sinadura eskuordetzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(15,4,4,'Formularioak kudeatzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(15,7,4,'Formularioen egoerak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(15,5,4,'Formularioak mantentzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(15,6,4,'Formulario motak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(16,0,4,'Txostenak kudeatzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(16,1,4,'Txosten-eskaerak');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(16,2,4,'Txostenak sortzea');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(16,4,3,'Txosten-postontzia');
Insert into A_PID (PID_APL,PID_PRO,PID_IDI,PID_DES) values(18,1,4,'Formulario-erabiltzaileak');
GO
