
-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y ESTADO PENDIENTE
SELECT E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS DESCRIPCION_PROCEDIMIENTO,COUNT(*) AS NUMERO_EXPEDIENTES
FROM E_EXP,E_PRO
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_EST=0
GROUP BY E_PRO.PRO_COD,E_PRO.PRO_DES,EXP_EST
ORDER BY E_PRO.PRO_DES DESC;


-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y ESTADO ANULADO (FINALIZACIÓN NO CONVENCIONAL)
SELECT E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS DESCRIPCION_PROCEDIMIENTO,COUNT(*) AS NUMERO_EXPEDIENTES
FROM E_EXP,E_PRO
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_EST=1
GROUP BY E_PRO.PRO_COD,E_PRO.PRO_DES,EXP_EST
ORDER BY E_PRO.PRO_DES DESC;


-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y ESTADO FINALIZADO
SELECT E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS DESCRIPCION_PROCEDIMIENTO,COUNT(*) AS NUMERO_EXPEDIENTES
FROM E_EXP,E_PRO
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_EST=9
GROUP BY E_PRO.PRO_COD,E_PRO.PRO_DES,EXP_EST
ORDER BY E_PRO.PRO_DES DESC;



-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y POR TIPO DE INICIO INSTANCIA DE PARTE
SELECT E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS DESCRIPCION_PROCEDIMIENTO,COUNT(*) AS NUM_EXPEDIENTES
FROM E_EXP,E_PRO, E_EXR
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_MUN=E_EXR.EXR_MUN AND E_EXP.EXP_EJE = E_EXR.EXR_EJE
AND E_EXP.EXP_NUM = E_EXR.EXR_NUM
AND E_EXR.EXR_TOP=0
GROUP BY E_EXR.EXR_TOP,E_PRO.PRO_COD,E_PRO.PRO_DES
ORDER BY E_PRO.PRO_DES DESC;


-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y QUE HAN SIDO INICIADOS DE OFICIO
SELECT PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,PRO.PRO_DES AS DESCRIPCION_PROCEDIMIENTO, COUNT(*) AS NUM_EXPEDIENTES
FROM E_EXP EXP,E_PRO PRO
WHERE EXP.EXP_PRO = PRO.PRO_COD AND EXP.EXP_MUN = PRO.PRO_MUN
AND EXP.EXP_NUM NOT IN (SELECT EXR_NUM FROM E_EXR 
                        WHERE E_EXR.EXR_TOP=0 
                        AND E_EXR.EXR_PRO=EXP.EXP_PRO)
GROUP BY PRO.PRO_COD,PRO.PRO_DES
ORDER BY PRO.PRO_DES DESC;



-- NÚMERO DE EXPEDIENTE POR PROCEDIMIENTO Y POR OFICINA TRAMITADORA
-- Muestra el cod procedimiento, descripcion, num expediente y nombre de unidad tramitadora
SELECT UOR_NOM,E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS NOMBRE_PROCEDIMIENTO, COUNT(*) AS NUMERO
FROM E_EXP,E_PRO,A_UOR
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD 
AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_UOR= A_UOR.UOR_COD 
GROUP BY A_UOR.UOR_COD,A_UOR.UOR_NOM,E_PRO.PRO_COD,E_PRO.PRO_DES
ORDER BY A_UOR.UOR_COD ASC;




-- NÚMERO DE EXPEDIENTES POR PROCEDIMIENTO Y POR UN RANGO DE FECHAS
SELECT E_PRO.PRO_COD AS CODIGO_PROCEDIMIENTO,E_PRO.PRO_DES AS NOMBRE_PROCEDIMIENTO, COUNT(*) AS NUMERO
FROM E_EXP,E_PRO
WHERE E_EXP.EXP_PRO = E_PRO.PRO_COD 
AND E_EXP.EXP_MUN = E_PRO.PRO_MUN
AND E_EXP.EXP_FEI BETWEEN TO_DATE('01/05/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') 
AND TO_DATE('31/05/2012 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
GROUP BY E_PRO.PRO_COD,E_PRO.PRO_DES
ORDER BY E_PRO.PRO_DES ASC;











