--Tarea #62575 Marcos Rama

INSERT INTO T_TID ( TID_COD, TID_DIN, TID_DUP, TID_PFI, TID_NML, TID_DES, TID_DG1, TID_TD1, TID_DG2, TID_TD2, TID_DG3, TID_TD3, TID_DG4, TID_TD4, TID_DG5, TID_TD5, TID_LMX, TID_TVA, TID_COD_ACCEDE ) 
	VALUES (8, 0, 0, 1, 0, 'W', 9, 'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL); 
	
INSERT INTO T_TID ( TID_COD, TID_DIN, TID_DUP, TID_PFI, TID_NML, TID_DES, TID_DG1, TID_TD1, TID_DG2, TID_TD2, TID_DG3, TID_TD3, TID_DG4, TID_TD4, TID_DG5, TID_TD5, TID_LMX, TID_TVA, TID_COD_ACCEDE ) 
	VALUES (9, 0, 0, 1, 0, 'U', 9, 'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', NULL);