/* Generated by Together */
package es.altia.agora.interfaces.user.web.terceros;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.terceros.mantenimiento.persistence.ProvinciasManager;
import es.altia.agora.business.terceros.mantenimiento.persistence.MunicipiosManager;
import es.altia.agora.business.terceros.mantenimiento.persistence.PaisesManager;
import es.altia.agora.business.terceros.ParametrosTerceroValueObject;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.common.service.config.Config;
import es.altia.common.service.config.ConfigServiceHelper;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class CargarDepuracionViasAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(CargarDepuracionViasAction.class.getName());
    protected static Config m_ConfigTechnical = ConfigServiceHelper.getConfig("techserver");

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("CargarDepuracionViasAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        ParametrosTerceroValueObject paramsTercero = (ParametrosTerceroValueObject)session.getAttribute("parametrosTercero");
        String codPais = paramsTercero.getPais();
        String codProvincia = paramsTercero.getProvincia();
        String codMunicipio = paramsTercero.getMunicipio();

        ProvinciasManager provinciasManager = ProvinciasManager.getInstance();
        MunicipiosManager municipiosManager = MunicipiosManager.getInstance();
        GeneralValueObject gVO = new GeneralValueObject();

        gVO.setAtributo("codPais", codPais);
        gVO.setAtributo("codProvincia", codProvincia);
        gVO.setAtributo("codMunicipio",codMunicipio);
        Vector provs = provinciasManager.getListaProvincias(gVO,params);
        Vector municipios = municipiosManager.getListaMunicipios(gVO,params);

        request.setAttribute("provincias", provs);
        request.setAttribute("municipios", municipios);
        request.setAttribute("codProvincia", codProvincia);
        request.setAttribute("codMunicipio",codMunicipio);
        request.setAttribute("codPais",codPais);

        if (request.getParameter("actionOrigen")==null || !request.getParameter("actionOrigen").equals("volver")) {
            session.removeAttribute("DepuracionVias.viasRepetidas");
        } else if (request.getParameter("actionOrigen").equals("volver")){
            request.setAttribute("codProvincia", request.getParameter("codProvincia"));
            request.setAttribute("codMunicipio",request.getParameter("codMunicipio"));
            request.setAttribute("actionOrigen","volver");
        }

        return (mapping.findForward("default"));
    }
}