/* Generated by Together */
package es.altia.agora.interfaces.user.web.terceros;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.terceros.persistence.TercerosManager;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.common.service.config.Config;
import es.altia.common.service.config.ConfigServiceHelper;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarDepuracionDomiciliosAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarDepuracionDomiciliosAction.class.getName());
    protected static Config m_ConfigTechnical = ConfigServiceHelper.getConfig("techserver");

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) {

        m_Log.info("EliminarDepuracionDomiciliosAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();
        int codUsuario = 0;
        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
            codUsuario = usuarioVO.getIdUsuario();
        }

        TerceroForm terceroForm = (TerceroForm) session.getAttribute("DepuracionTerceros.tercero");
        String codTercero = terceroForm.getCodTercero();
        String codDomPrincipal = request.getParameter("codDomPrincipal");

        String[] codDomAEliminar = (request.getParameter("codDomAEliminar")).split(",");
        GeneralValueObject gVO = new GeneralValueObject();
        gVO.setAtributo("codTercero", codTercero);
        gVO.setAtributo("codDomPrincipal", codDomPrincipal);
        try {
            TercerosManager.getInstance().depurarDomicilios(params, gVO, codDomAEliminar, codUsuario);
        } catch (Exception e) {
            return (mapping.findForward("error"));
        }
        Vector domicilios = terceroForm.getDomicilios();
        for (int k=0;k<domicilios.size();k++) {
            for (int j=0;j<codDomAEliminar.length;j++) {
                if (codDomAEliminar[j].equals(((DomicilioForm)domicilios.elementAt(k)).getCodDomicilio())) {
                    domicilios.remove(k);
                    k--;
                    break;
                 }
            }
        }
        terceroForm.setCodDomPrincipal(codDomPrincipal);
        terceroForm.setDomicilios(domicilios);
        session.setAttribute("DepuracionTerceros.tercero", terceroForm);
        return (mapping.findForward("default"));
    }
}