--------------------------------------------------------------------------
-- FLEXIA 10.4 
-- Altia Consultores 
-- Scripts creación BD flexia 
-- Oracle
-- Creacións de las tablas del esquema generico
-- Ejecutar con usuario del esquema generico
--------------------------------------------------------------------------

spool 3_crea_tablas_generico.log
SET ECHO ON;

-- Modulo de Administracion

CREATE TABLE A_AML (	
	AML_COD NUMBER(3,0) NOT NULL, 
	AML_CMP VARCHAR2(3) NOT NULL, 
	AML_LENG VARCHAR2(1) NOT NULL, 
	AML_VALOR VARCHAR2(255), 
	PRIMARY KEY (AML_COD, AML_CMP, AML_LENG)
);

COMMENT ON COLUMN A_AML.AML_COD IS 'Código Área';
COMMENT ON COLUMN A_AML.AML_CMP IS 'Código Campo MultiLenguaje. (NOM = Nombre)'; 
COMMENT ON COLUMN A_AML.AML_LENG IS 'Idioma del Campo';
COMMENT ON COLUMN A_AML.AML_VALOR IS 'Contenido del Campo';
COMMENT ON TABLE A_AML IS 'MultiLenguaje de Areas';
 

CREATE TABLE A_APL (	
	APL_COD NUMBER(3,0) NOT NULL, 
	APL_NOM VARCHAR2(80) NOT NULL, 
	APL_EXE VARCHAR2(255) NOT NULL, 
	APL_SEG NUMBER(1,0) NOT NULL, 
	APL_ADF NUMBER(1,0) NOT NULL, 
	APL_DIC VARCHAR2(255), 
	APL_REP VARCHAR2(255), 
	APL_VER VARCHAR2(30), 
	APL_ENT NUMBER(1,0) NOT NULL, 
	APL_EJE NUMBER(1,0) NOT NULL, 
	APL_ICO VARCHAR2(255) DEFAULT '/images/escritorio/windows2000/icon_default.gif' NOT NULL, 
	CONSTRAINT PK_APL PRIMARY KEY (APL_COD)
);


COMMENT ON COLUMN A_APL.APL_COD IS 'Codigo de aplicacion';
COMMENT ON COLUMN A_APL.APL_NOM IS 'Nombre de aplicacion';
COMMENT ON COLUMN A_APL.APL_EXE IS 'Ubicacion del iniciador de la aplicacion';
COMMENT ON COLUMN A_APL.APL_SEG IS 'Tipo de seguridad';
COMMENT ON COLUMN A_APL.APL_ADF IS 'Tipo de acceso por defecto';
COMMENT ON COLUMN A_APL.APL_DIC IS 'Base de datos de diccionario';
COMMENT ON COLUMN A_APL.APL_REP IS 'Ruta de los listados de la aplicacion'; 
COMMENT ON COLUMN A_APL.APL_VER IS 'Version de la aplicacion';
COMMENT ON COLUMN A_APL.APL_ENT IS 'Trabaja con entidades';
COMMENT ON COLUMN A_APL.APL_EJE IS 'Trabaja con ejercicios';
COMMENT ON TABLE A_APL  IS 'Aplicaciones registradas en el sistema de administracion de aplicaciones';

  
CREATE TABLE A_ARE (	
	ARE_COD NUMBER(3,0) NOT NULL, 
	PRIMARY KEY (ARE_COD)
);

COMMENT ON COLUMN A_ARE.ARE_COD IS 'Codigo area';
COMMENT ON TABLE A_ARE  IS 'AREA';
 

CREATE TABLE A_GRU (	
	GRU_COD NUMBER(3,0) NOT NULL, 
	GRU_NOM VARCHAR2(40) NOT NULL, 
	CONSTRAINT PK_GRU PRIMARY KEY (GRU_COD)
);

COMMENT ON COLUMN A_GRU.GRU_COD IS 'Codigo';
COMMENT ON COLUMN A_GRU.GRU_NOM IS 'Descripcion del Grupo';
COMMENT ON TABLE A_GRU IS 'Grupos de usuarios de las organizaciones';


CREATE TABLE A_IDI (	
	IDI_COD NUMBER(1,0) NOT NULL, 
	IDI_NOM VARCHAR2(20) NOT NULL,
	IDI_CLAVE CHAR(2), 
	CONSTRAINT PK_IDI PRIMARY KEY (IDI_COD)
);

COMMENT ON COLUMN A_IDI.IDI_COD IS 'Codigo de Idioma';
COMMENT ON COLUMN A_IDI.IDI_NOM IS 'Nombre';
COMMENT ON COLUMN A_IDI.IDI_CLAVE IS 'Sufijo usado para generación de documentos PDF';
COMMENT ON TABLE A_IDI IS 'Tablas de idiomas en los que esta disponible la aplicacion.';
 

CREATE TABLE A_CSS (
	CSS_COD NUMBER(3,0) NOT NULL,
 	CSS_RUTA VARCHAR2(4000 BYTE) NOT NULL,
 	CSS_DES VARCHAR2(4000 BYTE) NOT NULL, 
 	CSS_GENERAL NUMBER(1,0) DEFAULT 0, 
	PRIMARY KEY (CSS_COD)
);


CREATE TABLE A_ORG (	
	ORG_COD NUMBER(3,0) NOT NULL, 
	ORG_DES VARCHAR2(80) NOT NULL, 
	ORG_MUN NUMBER(5,0), 
	ORG_ICO VARCHAR2(30), 
	ORG_NUM NUMBER(1,0), 
	org_css NUMBER(3,0) default 1,
	CONSTRAINT PK_ORG PRIMARY KEY (ORG_COD),
	FOREIGN KEY (org_css) REFERENCES a_css(css_cod)
);

COMMENT ON TABLE A_ORG IS 'Organizaciones definidas en la instalacion';


CREATE TABLE A_ORGEX (	
	ORGEX_COD NUMBER(3,0) NOT NULL, 
	ORGEX_DES VARCHAR2(100) NOT NULL, 
	CONSTRAINT PK_A_ORGEX PRIMARY KEY (ORGEX_COD)
);


CREATE TABLE A_UOREX (	
	UOREX_COD NUMBER(3,0) NOT NULL, 
	UOREX_ORG NUMBER(3,0) NOT NULL, 
	UOREX_NOM VARCHAR2(100) NOT NULL, 
	CONSTRAINT PK_A_UOREX PRIMARY KEY (UOREX_COD, UOREX_ORG)
);


CREATE TABLE A_ENT (	
	ENT_ORG NUMBER(3,0) NOT NULL, 
	ENT_COD NUMBER(3,0) NOT NULL, 
	ENT_NOM VARCHAR2(80) NOT NULL, 
	ENT_DTR VARCHAR2(255), 
	ENT_TIP VARCHAR2(1) NOT NULL, 
	CONSTRAINT PK_ENT PRIMARY KEY (ENT_ORG, ENT_COD),
	CONSTRAINT FK_ENT_REL_ORG_E_ORG FOREIGN KEY (ENT_ORG)
		REFERENCES A_ORG (ORG_COD)
);

CREATE INDEX REL_ORG_ENT_FK ON A_ENT (ENT_ORG);

COMMENT ON COLUMN A_ENT.ENT_ORG IS 'Codigo de Organizacion';
COMMENT ON COLUMN A_ENT.ENT_COD IS 'Codigo de entidad';
COMMENT ON COLUMN A_ENT.ENT_NOM IS 'Nombre';
COMMENT ON COLUMN A_ENT.ENT_DTR IS 'Directorio de trabajo';
COMMENT ON COLUMN A_ENT.ENT_TIP IS 'Tipo de Entidad';
COMMENT ON TABLE A_ENT IS 'ENTIDADES';


CREATE TABLE A_AAE (	
	AAE_APL NUMBER(3,0) NOT NULL, 
	AAE_ORG NUMBER(3,0) NOT NULL, 
	AAE_ENT NUMBER(3,0) NOT NULL, 
	AAE_LIC VARCHAR2(20), 
	CONSTRAINT PK_AAE PRIMARY KEY (AAE_APL, AAE_ORG, AAE_ENT), 
	CONSTRAINT FK_AAE_REL_ENT_A_ENT FOREIGN KEY (AAE_ORG, AAE_ENT)
		REFERENCES A_ENT (ENT_ORG, ENT_COD), 
	CONSTRAINT FK_AAE_REL_APL_A_APL FOREIGN KEY (AAE_APL)
		REFERENCES A_APL (APL_COD)
);

COMMENT ON COLUMN A_AAE.AAE_APL IS 'Codigo de Aplicacion';
COMMENT ON COLUMN A_AAE.AAE_ORG IS 'Codigo de Organizacion';
COMMENT ON COLUMN A_AAE.AAE_ENT IS 'Codigo de Entidad';
COMMENT ON COLUMN A_AAE.AAE_LIC IS 'Codigo de licencia';
COMMENT ON TABLE A_AAE IS 'APLICACIONES AUTORIZADAS A ENTIDADES';

CREATE INDEX REL_ENT_AAE_FK ON A_AAE (AAE_ORG, AAE_ENT);
CREATE INDEX REL_APL_AAE_FK ON A_AAE (AAE_APL);


CREATE TABLE A_USU (	
	USU_COD NUMBER(4,0) NOT NULL, 
	USU_IDI NUMBER(1,0) NOT NULL, 
	USU_APL NUMBER(3,0), 
	USU_LOG VARCHAR2(255) NOT NULL, 
	USU_PAS VARCHAR2(40) NOT NULL, 
	USU_NOM VARCHAR2(40) NOT NULL, 
	USU_ACT NUMBER(1,0) NOT NULL, 
	USU_CON NUMBER(1,0) NOT NULL, 
	USU_LIS NUMBER(1,0) NOT NULL, 
	USU_TEB NUMBER(1,0) NOT NULL, 
	USU_TDM NUMBER(1,0) NOT NULL, 
	USU_ICO NUMBER(1,0) NOT NULL, 
	USU_MPR NUMBER(1,0) NOT NULL, 
	USU_IGS VARCHAR2(255), 
	USU_IGN VARCHAR2(255), 
	USU_IPS VARCHAR2(255), 
	USU_IPN VARCHAR2(255), 
	USU_CBQ NUMBER(15,0), 
	USU_ICB VARCHAR2(255), 
	USU_NIF VARCHAR2(10), 
	USU_FIRMANTE NUMBER(1,0) DEFAULT 0, 
	USU_EMAIL VARCHAR2(100) DEFAULT ' ', 
	USU_FIRMA LONG RAW, 
	USU_TIPO_FIRMA VARCHAR2(25), 
	USU_BLQ NUMBER(1,0) DEFAULT 0 NOT NULL,
	USU_FBA DATE, 
	CONSTRAINT PK_USU PRIMARY KEY (USU_COD), 
	CONSTRAINT FK_USU_REL_IDI_U_IDI FOREIGN KEY (USU_IDI)
		REFERENCES A_IDI (IDI_COD), 
	CONSTRAINT FK_USU_REL_APL_U_APL FOREIGN KEY (USU_APL)
		REFERENCES A_APL (APL_COD)
);
 
COMMENT ON COLUMN A_USU.USU_COD IS 'Codigo de usuario';
COMMENT ON COLUMN A_USU.USU_IDI IS 'Idioma por defecto';
COMMENT ON COLUMN A_USU.USU_LOG IS 'Login';
COMMENT ON COLUMN A_USU.USU_PAS IS 'Password';
COMMENT ON COLUMN A_USU.USU_NOM IS 'Nombre de usuario';
COMMENT ON COLUMN A_USU.USU_ACT IS 'Puede actualizar';
COMMENT ON COLUMN A_USU.USU_CON IS 'Puede consultar';
COMMENT ON COLUMN A_USU.USU_LIS IS 'Puede listar';
COMMENT ON COLUMN A_USU.USU_TEB IS 'Tiempo maximo en bloqueos';
COMMENT ON COLUMN A_USU.USU_TDM IS 'Tipo de menu';
COMMENT ON COLUMN A_USU.USU_ICO IS 'Utilizar iconos';
COMMENT ON COLUMN A_USU.USU_MPR IS 'Mostrar los procesos restringidos';
COMMENT ON COLUMN A_USU.USU_IGS IS 'Icono grupos de procesos autorizados';
COMMENT ON COLUMN A_USU.USU_IGN IS 'Icono grupo de procesos no autorizados';
COMMENT ON COLUMN A_USU.USU_IPS IS 'Icono procesos autorizados';
COMMENT ON COLUMN A_USU.USU_IPN IS 'Icono procesos no autorizados';
COMMENT ON COLUMN A_USU.USU_CBQ IS 'Color para los campos bloqueados';
COMMENT ON COLUMN A_USU.USU_ICB IS 'Icono para los campos bloqueados';
COMMENT ON COLUMN A_USU.USU_BLQ IS 'Indicado bloqueo 1=Si/0=No';
COMMENT ON COLUMN A_USU.USU_FBA IS 'Fecha de baja';
COMMENT ON TABLE A_USU IS 'Usuarios del sistema';

CREATE INDEX REL_IDI_USU_FK ON A_USU (USU_IDI);
CREATE INDEX REL_APL_USU_FK ON A_USU (USU_APL);
 
 CREATE TABLE A_USU_ROTACION_PASS 
(
 COD_PASS NUMBER(4, 0) NOT NULL,
 USU_PASS VARCHAR2(40 BYTE) NOT NULL, 
 FEC_ALTA DATE,   
 USU_COD NUMBER(4,0) NOT NULL,
 CONSTRAINT A_USU_ROTACION_PAS_PK PRIMARY KEY(COD_PASS),
 FOREIGN KEY ("USU_COD") REFERENCES A_USU("USU_COD") ENABLE);
 
 
CREATE TABLE USUARIO_PROC_RESTRINGIDO(
	PRO_COD VARCHAR2(5 BYTE) NOT NULL,	
	USU_COD NUMBER(4,0) NOT NULL,  
	ORG_COD NUMBER(3,0) NOT NULL,	
	ENT_COD NUMBER(3,0) NOT NULL,	
	FOREIGN KEY (USU_COD) REFERENCES A_USU(USU_COD) ON DELETE CASCADE,
	FOREIGN KEY (ORG_COD)	REFERENCES A_ORG(ORG_COD) ON DELETE CASCADE,			
	PRIMARY KEY(PRO_COD,USU_COD,ORG_COD,ENT_COD));
commit;


CREATE TABLE A_AAU (	
	AAU_APL NUMBER(3,0) NOT NULL, 
	AAU_USU NUMBER(4,0) NOT NULL, 
	AAU_ORG NUMBER(3,0), 
	AAU_ENT NUMBER(3,0), 
	CONSTRAINT PK_AAU PRIMARY KEY (AAU_APL, AAU_USU), 
	CONSTRAINT FK_AAU_REL_ENT_A_ENT FOREIGN KEY (AAU_ORG, AAU_ENT)
		REFERENCES A_ENT (ENT_ORG, ENT_COD), 
	CONSTRAINT FK_AAU_REL_USU_A_USU FOREIGN KEY (AAU_USU)
		REFERENCES A_USU (USU_COD), 
	CONSTRAINT FK_AAU_REL_APL_A_APL FOREIGN KEY (AAU_APL)
		REFERENCES A_APL (APL_COD)
);
 
COMMENT ON COLUMN A_AAU.AAU_APL IS 'Codigo de Aplicacion';
COMMENT ON COLUMN A_AAU.AAU_USU IS 'Codigo de Usuario';
COMMENT ON COLUMN A_AAU.AAU_ORG IS 'Organizacion';
COMMENT ON COLUMN A_AAU.AAU_ENT IS 'Entidad';
COMMENT ON TABLE A_AAU IS 'APLICACIONES AUTORIZADAS A USUARIOS';

CREATE INDEX REL_USU_AAU_FK ON A_AAU (AAU_USU)  ;
CREATE INDEX REL_APL_AAU_FK ON A_AAU (AAU_APL);
CREATE INDEX REL_ENT_AAU_FK ON A_AAU (AAU_ORG, AAU_ENT) ;


CREATE TABLE A_AID (	
	AID_APL NUMBER(3,0) NOT NULL, 
	AID_IDI NUMBER(1,0) NOT NULL, 
	AID_TEX VARCHAR2(80) NOT NULL, 
	CONSTRAINT PK_AID PRIMARY KEY (AID_APL, AID_IDI), 
	CONSTRAINT FK_AID_REL_IDI_A_IDI FOREIGN KEY (AID_IDI)
		REFERENCES  A_IDI (IDI_COD), 
	CONSTRAINT FK_AID_REL_APL_A_APL FOREIGN KEY (AID_APL)
		REFERENCES  A_APL (APL_COD)
);

COMMENT ON COLUMN A_AID.AID_APL IS 'Codigo de aplicacion';
COMMENT ON COLUMN A_AID.AID_IDI IS 'Codigo de Idioma';
COMMENT ON COLUMN A_AID.AID_TEX IS 'Nombre de la aplicacion traducido';
COMMENT ON TABLE A_AID  IS 'Tabla con las descripciones traducidas de las aplicaciones';

CREATE INDEX REL_APL_AID_FK ON A_AID (AID_APL);
CREATE INDEX REL_IDI_AID_FK ON A_AID (AID_IDI);


CREATE TABLE A_EEA (	
	EEA_APL NUMBER(3,0) NOT NULL, 
	AAE_ORG NUMBER(3,0) NOT NULL, 
	EEA_ENT NUMBER(3,0) NOT NULL, 
	EEA_EJE NUMBER(4,0) NOT NULL, 
	EEA_EST VARCHAR2(1) NOT NULL, 
	EEA_BDE VARCHAR2(255), 
	EEA_VBD VARCHAR2(30) NOT NULL, 
	EEA_UBD VARCHAR2(18), 
	EEA_PWD VARCHAR2(18), 
	EEA_DBMS VARCHAR2(30), 
	EEA_ARQ VARCHAR2(10), 
	EEA_LOG VARCHAR2(255), 
	EEA_TRA NUMBER(1,0), 
	EEA_QTO NUMBER(3,0), 
	EEA_PWDBD VARCHAR2(15), 
	EEA_DB VARCHAR2(255), 
	EEA_ODBC LONG, 
	CONSTRAINT PK_EEA PRIMARY KEY (EEA_APL, AAE_ORG, EEA_ENT, EEA_EJE), 
	CONSTRAINT FK_EEA_REL_AAE_E_AAE FOREIGN KEY (EEA_APL, AAE_ORG, EEA_ENT)
		REFERENCES A_AAE (AAE_APL, AAE_ORG, AAE_ENT)
);

COMMENT ON COLUMN A_EEA.EEA_APL IS 'Aplicacion';
COMMENT ON COLUMN A_EEA.AAE_ORG IS 'Organizacion';
COMMENT ON COLUMN A_EEA.EEA_ENT IS 'Entidad';
COMMENT ON COLUMN A_EEA.EEA_EJE IS 'Ejercicio';
COMMENT ON COLUMN A_EEA.EEA_EST IS 'Estado';
COMMENT ON COLUMN A_EEA.EEA_BDE IS 'Base de datos';
COMMENT ON COLUMN A_EEA.EEA_VBD IS 'Version de la base de datos';
COMMENT ON COLUMN A_EEA.EEA_UBD IS 'Usuario de acceso a la base de datos';
COMMENT ON COLUMN A_EEA.EEA_PWD IS 'Clave de acceso a la base de datos';
COMMENT ON COLUMN A_EEA.EEA_DBMS IS 'Tipo Origen de Datos';
COMMENT ON COLUMN A_EEA.EEA_ARQ IS 'Arquitectura';
COMMENT ON COLUMN A_EEA.EEA_LOG IS 'Fichero para trazas de error';
COMMENT ON COLUMN A_EEA.EEA_TRA IS 'Transacciones';
COMMENT ON COLUMN A_EEA.EEA_QTO IS 'Tiempo de espera';
COMMENT ON COLUMN A_EEA.EEA_PWDBD IS 'Clave de proteccion de la base de datos';
COMMENT ON COLUMN A_EEA.EEA_DB IS 'Base de datos para origen generico';
COMMENT ON COLUMN A_EEA.EEA_ODBC IS 'Configuracion del origen de datos asociado';
COMMENT ON TABLE A_EEA  IS 'EJERCICIOS POR ENTIDAD Y APLICACION';

CREATE INDEX REL_AAE_EEA_FK ON  A_EEA (AAE_ORG, EEA_ENT, EEA_APL);
 

CREATE TABLE A_MNU (	
	MNU_ORG NUMBER(3,0) NOT NULL, 
	MNU_APL NUMBER(3,0) NOT NULL, 
	MNU_COD NUMBER(2,0) NOT NULL, 
	MNU_DES VARCHAR2(60) NOT NULL, 
	MNU_ACT NUMBER(1,0) NOT NULL, 
	CONSTRAINT PK_MNU PRIMARY KEY (MNU_ORG, MNU_APL, MNU_COD), 
	CONSTRAINT FK_MNU_REL_ORG_M_ORG FOREIGN KEY (MNU_ORG)
		REFERENCES A_ORG (ORG_COD), 
	CONSTRAINT FK_MNU_REL_APL_M_APL FOREIGN KEY (MNU_APL)
		REFERENCES A_APL (APL_COD)
);

COMMENT ON COLUMN A_MNU.MNU_ORG IS 'Organizacion';
COMMENT ON COLUMN A_MNU.MNU_APL IS 'Aplicacion';
COMMENT ON COLUMN A_MNU.MNU_COD IS 'Codigo de menu';
COMMENT ON COLUMN A_MNU.MNU_DES IS 'Descripcion';
COMMENT ON COLUMN A_MNU.MNU_ACT IS 'Activo';
COMMENT ON TABLE A_MNU  IS 'Menus de la organizacion';
 
CREATE INDEX REL_ORG_MNU_FK ON A_MNU (MNU_ORG);
CREATE INDEX REL_APL_MNU_FK ON A_MNU (MNU_APL);


CREATE TABLE A_MOR (	
	MOR_ORG NUMBER(3,0) NOT NULL, 
	MOR_APL NUMBER(3,0) NOT NULL, 
	MOR_MNU NUMBER(2,0) NOT NULL, 
	MOR_ELE NUMBER(4,0) NOT NULL, 
	MOR_PRO NUMBER(4,0) NOT NULL, 
	MOR_VIS NUMBER(1,0) NOT NULL, 
	MOR_DES VARCHAR2(80), 
	MOR_PAD NUMBER(4,0) NOT NULL, 
	CONSTRAINT PK_MOR PRIMARY KEY (MOR_ORG, MOR_APL, MOR_MNU, MOR_ELE), 
	CONSTRAINT FK_MOR_REL_MNU_M_MNU FOREIGN KEY (MOR_ORG, MOR_APL, MOR_MNU)
		REFERENCES A_MNU (MNU_ORG, MNU_APL, MNU_COD)
);

COMMENT ON COLUMN A_MOR.MOR_ORG IS 'Codigo de Organizacion';
COMMENT ON COLUMN A_MOR.MOR_APL IS 'Codigo de Aplicacion';
COMMENT ON COLUMN A_MOR.MOR_MNU IS 'Codigo de Menu';
COMMENT ON COLUMN A_MOR.MOR_ELE IS 'Elemento de menu';
COMMENT ON COLUMN A_MOR.MOR_PRO IS 'Proceso que lanza';
COMMENT ON COLUMN A_MOR.MOR_VIS IS 'Proceso visible';
COMMENT ON COLUMN A_MOR.MOR_DES IS 'Descripcion del menu';
COMMENT ON COLUMN A_MOR.MOR_PAD IS 'Elemento padre';
COMMENT ON TABLE A_MOR  IS 'Configuracion del menu de una organizacion';

CREATE INDEX REL_MNU_MOR_FK ON A_MOR (MOR_ORG, MOR_APL, MOR_MNU);
CREATE INDEX REL_PRO_MOR_FK ON A_MOR (MOR_PRO);


CREATE TABLE A_OUS (	
	OUS_ORG NUMBER(3,0) NOT NULL, 
	OUS_USU NUMBER(4,0) NOT NULL, 
	CONSTRAINT PK_OUS PRIMARY KEY (OUS_ORG, OUS_USU), 
	CONSTRAINT FK_OUS_REL_ORG_O_ORG FOREIGN KEY (OUS_ORG)
		REFERENCES A_ORG (ORG_COD), 
	CONSTRAINT FK_OUS_REL_USU_O_USU FOREIGN KEY (OUS_USU)
		REFERENCES A_USU (USU_COD)
);

COMMENT ON COLUMN A_OUS.OUS_ORG IS 'Organizacion';
COMMENT ON COLUMN A_OUS.OUS_USU IS 'Usuario';
COMMENT ON TABLE A_OUS  IS 'Organizaciones a las que tiene acceso un usuario';
 
CREATE INDEX REL_ORG_OUS_FK ON A_OUS (OUS_ORG);
CREATE INDEX REL_USU_OUS_FK ON A_OUS (OUS_USU);


CREATE TABLE A_PRO (	
	PRO_APL NUMBER(3,0) NOT NULL, 
	PRO_COD NUMBER(4,0) NOT NULL, 
	PRO_TPR VARCHAR2(1) NOT NULL, 
	PRO_FRM VARCHAR2(255), 
	PRO_TAC NUMBER(2,0), 
	CONSTRAINT PK_PRO PRIMARY KEY (PRO_APL, PRO_COD), 
	CONSTRAINT FK_PRO_REL_APL_P_APL FOREIGN KEY (PRO_APL)
		REFERENCES A_APL (APL_COD)
);

COMMENT ON COLUMN A_PRO.PRO_APL IS 'Aplicacion';
COMMENT ON COLUMN A_PRO.PRO_COD IS 'Codigo del proceso';
COMMENT ON COLUMN A_PRO.PRO_TPR IS 'Tipo de Proceso';
COMMENT ON COLUMN A_PRO.PRO_FRM IS 'Nombre del formulario asociado';
COMMENT ON COLUMN A_PRO.PRO_TAC IS 'Tipo de proceso a iniciar';
COMMENT ON TABLE A_PRO IS 'Procesos que componen las aplicaciones';

CREATE INDEX REL_APL_PRO_FK ON A_PRO (PRO_APL);


CREATE TABLE A_PID (	
	PID_APL NUMBER(3,0) NOT NULL, 
	PID_PRO NUMBER(4,0) NOT NULL, 
	PID_IDI NUMBER(1,0) NOT NULL, 
	PID_DES VARCHAR2(80) NOT NULL, 
	CONSTRAINT PK_PID PRIMARY KEY (PID_APL, PID_PRO, PID_IDI), 
	CONSTRAINT FK_PID_REL_IDI_P_IDI FOREIGN KEY (PID_IDI)
		REFERENCES A_IDI (IDI_COD), 
	CONSTRAINT FK_PID_REL_PRO_P_PRO FOREIGN KEY (PID_APL, PID_PRO)
		REFERENCES A_PRO (PRO_APL, PRO_COD)
);

COMMENT ON COLUMN A_PID.PID_APL IS 'Aplicacion';
COMMENT ON COLUMN A_PID.PID_PRO IS 'Codigo de Proceso';
COMMENT ON COLUMN A_PID.PID_IDI IS 'Codigo de Idioma';
COMMENT ON COLUMN A_PID.PID_DES IS 'Descripcion de la opcion de menu';
COMMENT ON TABLE A_PID IS 'Procesos en los diferentes idiomas registrados en el sistema';

CREATE INDEX REL_PRO_PID_FK ON A_PID (PID_APL, PID_PRO) ;
CREATE INDEX REL_IDI_PID_FK ON A_PID (PID_IDI);
 

CREATE TABLE A_RPG (	
	RPG_GRU NUMBER(3,0) NOT NULL, 
	RPG_ORG NUMBER(3,0) NOT NULL, 
	RPG_ENT NUMBER(3,0) NOT NULL, 
	RPG_APL NUMBER(3,0) NOT NULL, 
	RPG_PRO NUMBER(4,0) NOT NULL, 
	RPG_TIP NUMBER(1,0) NOT NULL, 
	CONSTRAINT PK_RPG PRIMARY KEY (RPG_GRU, RPG_ORG, RPG_ENT, RPG_APL, RPG_PRO), 
	CONSTRAINT FK_RPG_REL_ENT_R_ENT FOREIGN KEY (RPG_ORG, RPG_ENT)
		REFERENCES A_ENT (ENT_ORG, ENT_COD), 
	CONSTRAINT FK_RPG_REL_GRU_R_GRU FOREIGN KEY (RPG_GRU)
		REFERENCES A_GRU (GRU_COD), 
	CONSTRAINT FK_RPG_REL_PRO_R_PRO FOREIGN KEY (RPG_APL, RPG_PRO)
		REFERENCES A_PRO (PRO_APL, PRO_COD)
);
 
COMMENT ON COLUMN A_RPG.RPG_GRU IS 'Grupo';
COMMENT ON COLUMN A_RPG.RPG_ORG IS 'Organizacion';
COMMENT ON COLUMN A_RPG.RPG_ENT IS 'Entidad';
COMMENT ON COLUMN A_RPG.RPG_APL IS 'Aplicacion';
COMMENT ON COLUMN A_RPG.RPG_PRO IS 'Proceso';
COMMENT ON COLUMN A_RPG.RPG_TIP IS 'Tipo de permiso';
COMMENT ON TABLE A_RPG IS 'Procesos a los que se tiene acceso o a los que se tiene restringido el acceso, por grupo de usuarios';
 
CREATE INDEX REL_PRO_RPG_FK ON A_RPG (RPG_APL, RPG_PRO);
CREATE INDEX REL_GRU_RPG_FK ON A_RPG (RPG_GRU);
CREATE INDEX REL_ENT_RPG_FK ON A_RPG (RPG_ORG, RPG_ENT);


CREATE TABLE A_RPU (	
	RPU_USU NUMBER(4,0) NOT NULL, 
	RPU_ORG NUMBER(3,0) NOT NULL, 
	RPU_ENT NUMBER(3,0) NOT NULL, 
	RPU_APL NUMBER(3,0) NOT NULL, 
	RPU_PRO NUMBER(4,0) NOT NULL, 
	RPU_TIP NUMBER(1,0) NOT NULL, 
	CONSTRAINT PK_RPU PRIMARY KEY (RPU_USU, RPU_ORG, RPU_ENT, RPU_APL, RPU_PRO), 
	CONSTRAINT FK_RPU_REL_ENT_R_ENT FOREIGN KEY (RPU_ORG, RPU_ENT)
		REFERENCES A_ENT (ENT_ORG, ENT_COD), 
	CONSTRAINT FK_RPU_REL_RPO_R_PRO FOREIGN KEY (RPU_APL, RPU_PRO)
		REFERENCES A_PRO (PRO_APL, PRO_COD), 
	CONSTRAINT FK_RPU_REL_USU_R_USU FOREIGN KEY (RPU_USU)
		REFERENCES A_USU (USU_COD)
);

COMMENT ON COLUMN A_RPU.RPU_USU IS 'Usuario';
COMMENT ON COLUMN A_RPU.RPU_ORG IS 'Organizacion';
COMMENT ON COLUMN A_RPU.RPU_ENT IS 'Entidad';
COMMENT ON COLUMN A_RPU.RPU_APL IS 'Aplicacion';
COMMENT ON COLUMN A_RPU.RPU_PRO IS 'Proceso';
COMMENT ON COLUMN A_RPU.RPU_TIP IS 'Tipo de permiso';
COMMENT ON TABLE A_RPU  IS 'Procesos a los que se tiene acceso o a los que se tiene restringido el acceso, por usuarios';

CREATE INDEX REL_RPO_RPU_FK ON A_RPU (RPU_APL, RPU_PRO);
CREATE INDEX REL_USU_RPU_FK ON A_RPU (RPU_USU);
CREATE INDEX REL_ENT_RPU_FK ON A_RPU (RPU_ORG, RPU_ENT);


CREATE TABLE A_TEX (	
	TEX_APL NUMBER(3,0) NOT NULL, 
	TEX_COD VARCHAR2(30) NOT NULL, 
	TEX_IDI NUMBER(1,0) NOT NULL, 
	TEX_DES VARCHAR2(255) NOT NULL, 
	TEX_USO NUMBER(1,0), 
	TEX_FEC DATE, 
	CONSTRAINT PK_TEX PRIMARY KEY (TEX_APL, TEX_COD, TEX_IDI), 
	CONSTRAINT FK_TEX_REL_IDI_T_IDI FOREIGN KEY (TEX_IDI)
		REFERENCES A_IDI (IDI_COD), 
	CONSTRAINT FK_TEX_REL_APL_T_APL FOREIGN KEY (TEX_APL)
		REFERENCES A_APL (APL_COD)
);

COMMENT ON COLUMN A_TEX.TEX_APL IS 'Aplicacion';
COMMENT ON COLUMN A_TEX.TEX_COD IS 'Codigo de Texto';
COMMENT ON COLUMN A_TEX.TEX_IDI IS 'Idioma';
COMMENT ON COLUMN A_TEX.TEX_DES IS 'Texto';
COMMENT ON COLUMN A_TEX.TEX_USO IS 'Estado';
COMMENT ON COLUMN A_TEX.TEX_FEC IS 'Fecha de creacion o modificacion';
COMMENT ON TABLE A_TEX IS 'Textos fijos que mostrara la aplicacion';

CREATE INDEX REL_APL_TEX_FK ON A_TEX (TEX_APL);
CREATE INDEX REL_IDI_TEX_FK ON A_TEX (TEX_IDI);
 

CREATE TABLE A_UAE (	
	UAE_USU NUMBER(4,0) NOT NULL, 
	UAE_ORG NUMBER(3,0) NOT NULL, 
	UAE_ENT NUMBER(3,0) NOT NULL, 
	UAE_APL NUMBER(3,0) NOT NULL, 
	UAE_EDE NUMBER(4,0), 
	CONSTRAINT PK_UAE PRIMARY KEY (UAE_USU, UAE_ORG, UAE_ENT, UAE_APL), 
	CONSTRAINT FK_UAE_REL_USU_U_USU FOREIGN KEY (UAE_USU)
		REFERENCES A_USU (USU_COD), 
	CONSTRAINT FK_UAE_REL_AAE_U_AAE FOREIGN KEY (UAE_APL, UAE_ORG, UAE_ENT)
		REFERENCES A_AAE (AAE_APL, AAE_ORG, AAE_ENT)
);

COMMENT ON COLUMN A_UAE.UAE_USU IS 'Usuario';
COMMENT ON COLUMN A_UAE.UAE_ORG IS 'Organizacion';
COMMENT ON COLUMN A_UAE.UAE_ENT IS 'Entidad';
COMMENT ON COLUMN A_UAE.UAE_APL IS 'Aplicacion';
COMMENT ON COLUMN A_UAE.UAE_EDE IS 'Ejercicio por defecto';
COMMENT ON TABLE A_UAE  IS 'ENTIDADES AUTORIZADAS POR APLICACION';

CREATE INDEX REL_USU_UAE_FK ON A_UAE (UAE_USU);
CREATE INDEX REL_AAE_UAE_FK ON A_UAE (UAE_ORG, UAE_ENT, UAE_APL);
 

CREATE TABLE A_UGO (	
	UGO_USU NUMBER(4,0) NOT NULL, 
	UGO_ORG NUMBER(3,0) NOT NULL, 
	UGO_ENT NUMBER(3,0) NOT NULL, 
	UGO_GRU NUMBER(3,0) NOT NULL, 
	UGO_APL NUMBER(3,0) NOT NULL, 
	CONSTRAINT PK_UGO PRIMARY KEY (UGO_USU, UGO_ORG, UGO_ENT, UGO_GRU, UGO_APL), 
	CONSTRAINT FK_UGO_REL_ENT_U_ENT FOREIGN KEY (UGO_ORG, UGO_ENT)
		REFERENCES A_ENT (ENT_ORG, ENT_COD), 
	CONSTRAINT FK_UGO_REL_GRU_U_GRU FOREIGN KEY (UGO_GRU)
		REFERENCES A_GRU (GRU_COD), 
	CONSTRAINT FK_UGO_REL_USU_U_USU FOREIGN KEY (UGO_USU)
		REFERENCES A_USU (USU_COD), 
	CONSTRAINT FK_UGO_REL_APL_U_APL FOREIGN KEY (UGO_APL)
		REFERENCES A_APL (APL_COD)
);

COMMENT ON COLUMN A_UGO.UGO_USU IS 'Usuario';
COMMENT ON COLUMN A_UGO.UGO_ORG IS 'Organizacion';
COMMENT ON COLUMN A_UGO.UGO_ENT IS 'Entidad';
COMMENT ON COLUMN A_UGO.UGO_GRU IS 'Grupo';
COMMENT ON COLUMN A_UGO.UGO_APL IS 'Aplicacion';
COMMENT ON TABLE A_UGO IS 'Pertenencia de usuarios a grupos de usuarios por aplicacion y entidad.';
 
CREATE INDEX REL_GRU_UGO_FK ON A_UGO (UGO_GRU);
CREATE INDEX REL_ENT_UGO_FK ON A_UGO (UGO_ORG, UGO_ENT);
CREATE INDEX REL_APL_UGO_FK ON A_UGO (UGO_APL);
CREATE INDEX REL_USU_UGO_FK ON A_UGO (UGO_USU);


CREATE TABLE A_UOU (	
	UOU_ORG NUMBER(3,0) NOT NULL, 
	UOU_ENT NUMBER(3,0) NOT NULL, 
	UOU_UOR NUMBER(3,0) NOT NULL, 
	UOU_USU NUMBER(4,0) NOT NULL, 
	UOU_CAR NUMBER(3,0), 
	CONSTRAINT PK_UOU PRIMARY KEY (UOU_ORG, UOU_ENT, UOU_UOR, UOU_USU), 
	CONSTRAINT FK_UOU_REL_USU_U_USU FOREIGN KEY (UOU_USU)
		REFERENCES A_USU (USU_COD)
);

COMMENT ON COLUMN A_UOU.UOU_ORG IS 'Organizacion';
COMMENT ON COLUMN A_UOU.UOU_ENT IS 'Entidad';
COMMENT ON COLUMN A_UOU.UOU_UOR IS 'Unidad Organica';
COMMENT ON COLUMN A_UOU.UOU_USU IS 'Usuario';
COMMENT ON TABLE A_UOU IS 'Pertenencia de usuarios a unidades organicas.';


CREATE TABLE USU_FIR_DEL (	
	USU_COD NUMBER(4,0) NOT NULL, 
	USU_DELEGADO NUMBER(4,0) NOT NULL, 
	FX_DESDE DATE NOT NULL, 
	FX_HASTA DATE NOT NULL, 
	PVERSION NUMBER(*,0) NOT NULL, 
	CONSTRAINT USU_FIR_DEL_PK PRIMARY KEY (USU_COD), 
	CONSTRAINT USU_FIR_DEL_FK FOREIGN KEY (USU_DELEGADO)
		REFERENCES A_USU (USU_COD) ON DELETE CASCADE
);


CREATE TABLE A_DIRECTIVA (
	    CODIGO VARCHAR2(64) NOT NULL,
	    APL  NUMBER(3,0) NOT NULL,
	    ETIQ VARCHAR2(30) NOT NULL,
	    CONSTRAINT PK_DIRECTIVA PRIMARY KEY (CODIGO)
  );
   
  COMMENT ON COLUMN A_DIRECTIVA.CODIGO IS 'Clave de la directiva';
  COMMENT ON COLUMN A_DIRECTIVA.APL IS 'Aplicación a la que se asocia esta directiva';
  COMMENT ON COLUMN A_DIRECTIVA.ETIQ IS 'Etiqueta de A_TEX para esta directiva';
  COMMENT ON TABLE A_DIRECTIVA IS 'Listado de directivas';
  
  
  CREATE TABLE A_USU_DIR (
      DIR VARCHAR2(64) NOT NULL,
      USU NUMBER(4,0) NOT NULL,
      CONSTRAINT PK_USU_DIR PRIMARY KEY (DIR,USU)
  );
  
  COMMENT ON COLUMN A_USU_DIR.DIR IS 'Directiva sobre la que tiene permiso un usuario';
  COMMENT ON COLUMN A_USU_DIR.USU IS 'Usuario que tiene permiso';
  COMMENT ON TABLE A_USU_DIR IS 'Permisos de usuarios sobre directivas';



-- Modulo de terceros.

CREATE TABLE T_ESC (	
	ESC_COD VARCHAR2(2) NOT NULL, 
	ESC_DES VARCHAR2(60) NOT NULL, 
	CONSTRAINT PK_T_ESC PRIMARY KEY (ESC_COD)
);

COMMENT ON COLUMN T_ESC.ESC_COD IS 'Codigo de Escalera (Ejemplos: EX= Exterior, YN= Interior, CN= Centro, CI= Centro Izquierda)'; 
COMMENT ON COLUMN T_ESC.ESC_DES IS 'Descripcion';
COMMENT ON TABLE T_ESC IS 'ESCALERAS';


CREATE TABLE T_PAI (	
	PAI_COD NUMBER(3,0) NOT NULL, 
	PAI_NOM VARCHAR2(25), 
	PAI_NOL VARCHAR2(50), 
	PAI_DCO VARCHAR2(1), 
	CONSTRAINT PK_T_PAI PRIMARY KEY (PAI_COD)
);

COMMENT ON COLUMN T_PAI.PAI_COD IS 'Codigo';
COMMENT ON COLUMN T_PAI.PAI_NOM IS 'Nombre';
COMMENT ON COLUMN T_PAI.PAI_NOL IS 'Nombre Largo';
COMMENT ON COLUMN T_PAI.PAI_DCO IS 'Digito de Control';
COMMENT ON TABLE T_PAI IS 'PAISES';
 

CREATE TABLE T_PLT (	
	PLT_COD VARCHAR2(3) NOT NULL, 
	PLT_DES VARCHAR2(60) NOT NULL, 
	CONSTRAINT PK_T_PLT PRIMARY KEY (PLT_COD)
);

COMMENT ON TABLE T_PLT IS 'PLANTAS (Ejemplos, PBJ= Planta Baja, S02=Sotano 2?, P01=Planta Primera)';


CREATE TABLE T_AUT (	
	AUT_PAI NUMBER(3,0) NOT NULL, 
	AUT_COD NUMBER(2,0) NOT NULL, 
	AUT_NOM VARCHAR2(25), 
	AUT_NOL VARCHAR2(50), 
	CONSTRAINT PK_T_AUT PRIMARY KEY (AUT_PAI, AUT_COD), 
	CONSTRAINT FK_T_AUT_REL_T_39_T_PAI FOREIGN KEY (AUT_PAI)
		REFERENCES T_PAI (PAI_COD)
);

COMMENT ON COLUMN T_AUT.AUT_PAI IS 'Pais';
COMMENT ON COLUMN T_AUT.AUT_COD IS 'Codigo';
COMMENT ON COLUMN T_AUT.AUT_NOM IS 'Nombre Oficial';
COMMENT ON COLUMN T_AUT.AUT_NOL IS 'Nombre Largo';
COMMENT ON TABLE T_AUT IS 'AUTONOMIAS';

CREATE INDEX REL_T_39_FK ON T_AUT (AUT_PAI);
 

CREATE TABLE T_PRV (	
	PRV_PAI NUMBER(3,0) NOT NULL, 
	PRV_COD NUMBER(2,0) NOT NULL, 
	PRV_AUT NUMBER(2,0), 
	PRV_NOM VARCHAR2(25), 
	PRV_NOL VARCHAR2(50), 
	CONSTRAINT PK_T_PRV PRIMARY KEY (PRV_PAI, PRV_COD), 
	CONSTRAINT FK_T_PRV_REL_T_41_T_AUT FOREIGN KEY (PRV_PAI, PRV_AUT)
		REFERENCES T_AUT (AUT_PAI, AUT_COD), 
	CONSTRAINT FK_T_PRV_REL_T_40_T_PAI FOREIGN KEY (PRV_PAI)
		REFERENCES T_PAI (PAI_COD)
);

COMMENT ON COLUMN T_PRV.PRV_PAI IS 'Pais';
COMMENT ON COLUMN T_PRV.PRV_COD IS 'Codigo de Provincia';
COMMENT ON COLUMN T_PRV.PRV_AUT IS 'Autonomia';
COMMENT ON COLUMN T_PRV.PRV_NOM IS 'Nombre Oficial';
COMMENT ON COLUMN T_PRV.PRV_NOL IS 'Nombre Largo';
COMMENT ON TABLE T_PRV IS 'PROVINCIAS';

CREATE INDEX REL_T_40_FK ON T_PRV (PRV_PAI);
CREATE INDEX REL_T_41_FK ON T_PRV (PRV_PAI, PRV_AUT);


CREATE TABLE T_PJU (	
	PJU_PAI NUMBER(3,0) NOT NULL, 
	PJU_PRV NUMBER(2,0) NOT NULL, 
	PJU_COD NUMBER(2,0) NOT NULL, 
	PJU_NOM VARCHAR2(25), 
	PJU_NOL VARCHAR2(50), 
	CONSTRAINT PK_T_PJU PRIMARY KEY (PJU_PAI, PJU_PRV, PJU_COD), 
	CONSTRAINT FK_T_PJU_REL_T_44_T_PRV FOREIGN KEY (PJU_PAI, PJU_PRV)
		REFERENCES T_PRV (PRV_PAI, PRV_COD)
);

COMMENT ON COLUMN T_PJU.PJU_PAI IS 'Pais';
COMMENT ON COLUMN T_PJU.PJU_PRV IS 'Provincia';
COMMENT ON COLUMN T_PJU.PJU_COD IS 'Codigo';
COMMENT ON COLUMN T_PJU.PJU_NOM IS 'Nombre';
COMMENT ON COLUMN T_PJU.PJU_NOL IS 'Nombre Largo';
COMMENT ON TABLE T_PJU  IS 'Partidos Judiciales';

CREATE INDEX REL_T_44_FK ON T_PJU (PJU_PAI, PJU_PRV);
 

CREATE TABLE T_MUN (	
	MUN_PAI NUMBER(3,0) NOT NULL, 
	MUN_PRV NUMBER(2,0) NOT NULL, 
	MUN_COD NUMBER(4,0) NOT NULL, 
	MUN_PJU NUMBER(2,0), 
	MUN_COM NUMBER(5,0), 
	MUN_NOM VARCHAR2(30), 
	MUN_NOL VARCHAR2(50), 
	MUN_DCO VARCHAR2(1), 
	MUN_SUP NUMBER(9,2), 
	MUN_ALT NUMBER(5,0), 
	MUN_KMC NUMBER(4,0), 
	MUN_LTN NUMBER(5,2), 
	MUN_LTS NUMBER(5,2), 
	MUN_LES NUMBER(5,2), 
	MUN_LOE NUMBER(5,2), 
	MUN_SIT VARCHAR2(1), 
	CONSTRAINT PK_T_MUN PRIMARY KEY (MUN_PAI, MUN_PRV, MUN_COD), 
	CONSTRAINT FK_T_MUN_REL_T_46_T_PJU FOREIGN KEY (MUN_PAI, MUN_PRV, MUN_PJU)
		REFERENCES T_PJU (PJU_PAI, PJU_PRV, PJU_COD), 
	CONSTRAINT FK_T_MUN_REL_T_47_T_PRV FOREIGN KEY (MUN_PAI, MUN_PRV)
		REFERENCES T_PRV (PRV_PAI, PRV_COD) ENABLE
);

COMMENT ON COLUMN T_MUN.MUN_PAI IS 'Pais';
COMMENT ON COLUMN T_MUN.MUN_PRV IS 'Provincia';
COMMENT ON COLUMN T_MUN.MUN_COD IS 'Codigo de Municipio';
COMMENT ON COLUMN T_MUN.MUN_PJU IS 'Partido Judicial';
COMMENT ON COLUMN T_MUN.MUN_COM IS 'Comarca';
COMMENT ON COLUMN T_MUN.MUN_NOM IS 'Nombre Oficial';
COMMENT ON COLUMN T_MUN.MUN_NOL IS 'Nombre Largo';
COMMENT ON COLUMN T_MUN.MUN_DCO IS 'Digito de Control INE';
COMMENT ON COLUMN T_MUN.MUN_SUP IS 'Superficie';
COMMENT ON COLUMN T_MUN.MUN_ALT IS 'Altitud';
COMMENT ON COLUMN T_MUN.MUN_KMC IS 'Kilometros a la Capital';
COMMENT ON COLUMN T_MUN.MUN_LTN IS 'Latitud Norte';
COMMENT ON COLUMN T_MUN.MUN_LTS IS 'Latitud Sur';
COMMENT ON COLUMN T_MUN.MUN_LES IS 'Longitud Este';
COMMENT ON COLUMN T_MUN.MUN_LOE IS 'Longitud Oeste';
COMMENT ON COLUMN T_MUN.MUN_SIT IS 'Situacion *A: Alta, O: Modificacion por Error, R: Modificacion con Rectificacion';
COMMENT ON TABLE T_MUN IS 'MUNICIPIOS';

CREATE INDEX REL_T_46_FK ON T_MUN (MUN_PAI, MUN_PRV, MUN_PJU);
CREATE INDEX REL_T_42_FK ON T_MUN (MUN_COM);
CREATE INDEX REL_T_47_FK ON T_MUN (MUN_PAI, MUN_PRV);



-- Modulo de expedientes.

CREATE TABLE A_CLS (	
	CLS_COD NUMBER(3,0) NOT NULL, 
	CLS_ORD NUMBER(3,0), 
	PRIMARY KEY (CLS_COD)
);

COMMENT ON COLUMN A_CLS.CLS_COD IS 'Codigo tramite';
COMMENT ON TABLE A_CLS IS 'CLASIFICACION TRAMITES';


CREATE TABLE A_CML (	
	CML_COD NUMBER(3,0) NOT NULL, 
	CML_CMP VARCHAR2(3) NOT NULL, 
	CML_LENG VARCHAR2(1) NOT NULL, 
	CML_VALOR VARCHAR2(255), 
	PRIMARY KEY (CML_COD, CML_CMP, CML_LENG), 
	FOREIGN KEY (CML_COD)
		REFERENCES  A_CLS (CLS_COD)
);

COMMENT ON COLUMN A_CML.CML_COD IS 'Codigo tramite';
COMMENT ON TABLE A_CML IS 'MultiLenguaje de Clasificacion de tramites';


CREATE TABLE A_TPR (	
	TPR_COD NUMBER(2,0) NOT NULL, 
	PRIMARY KEY (TPR_COD)
);

COMMENT ON COLUMN A_TPR.TPR_COD IS 'Identificador Unico de Tipo de Procedimiento';
COMMENT ON TABLE A_TPR IS 'TIPOS DE PROCEDIMIENTOS';
 

CREATE TABLE A_TPML (	
	TPML_COD NUMBER(2,0) NOT NULL, 
	TPML_CMP VARCHAR2(3) NOT NULL, 
	TPML_LENG VARCHAR2(1) NOT NULL, 
	TPML_VALOR VARCHAR2(255), 
	PRIMARY KEY (TPML_COD, TPML_CMP, TPML_LENG), 
	FOREIGN KEY (TPML_COD)
		REFERENCES  A_TPR (TPR_COD)
);

COMMENT ON COLUMN A_TPML.TPML_COD IS 'Identificador Unico de Tipo de Procedimiento';
COMMENT ON COLUMN A_TPML.TPML_CMP IS 'Codigo Campo Multilenguaje. (NOM = Nombre)';
COMMENT ON COLUMN A_TPML.TPML_LENG IS 'Idioma del Campo';
COMMENT ON COLUMN A_TPML.TPML_VALOR IS 'Contenido del Campo';
COMMENT ON TABLE A_TPML  IS 'MultiLenguaje de Tipo Procedimiento';

--Se crea aqui porque necesita del grant select del script posterior
CREATE MATERIALIZED VIEW v_mpp
build IMMEDIATE 
REFRESH complete NEXT SYSDATE + 30 AS
select mun_cod, prv_cod, pai_cod, mun_nom, prv_nom , pai_nom 
from t_mun 
left join t_prv on (prv_pai =mun_pai and prv_cod = mun_prv)
left join t_pai on (prv_pai = pai_cod);

-- Salida al sistema
spool off;
quit;
