/* Generated by Together */

package es.altia.agora.technical;

import es.altia.common.service.config.*;


public class BeanHelper {
    private static Config m_Config = ConfigServiceHelper.getConfig("techserver");
    private static Config m_ConfigError = ConfigServiceHelper.getConfig("error");

}
