/**
 * LangaiEECC.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package es.altia.agora.webservice.tercero.servicios.lanbide.cliente;

public interface LangaiEECC extends java.rmi.Remote {
    public java.util.Vector consultaSimplePF(java.lang.String cod_centro_usu, java.lang.String cod_ubic_usu, java.lang.String tipoDoc, java.lang.String numDoc, java.lang.String gen_per_corr, java.lang.String nombrePF, java.lang.String apellido1PF, java.lang.String apellido2PF, java.lang.String idioma, es.altia.agora.webservice.tercero.servicios.lanbide.cliente.PersonaFisicaWSValueObject personaFisicaWSValueObject, es.altia.agora.webservice.tercero.servicios.lanbide.cliente.EntidadesComunesWSValueObject entidadesComunesWSValueObject) throws java.rmi.RemoteException;
    public java.util.Vector consultaSimilaresPF(java.lang.String cod_centro_usu, java.lang.String cod_ubic_usu, java.lang.String tipoDoc, java.lang.String numDoc, java.lang.String gen_per_corr, java.lang.String nombrePF, java.lang.String apellido1PF, java.lang.String apellido2PF, java.lang.String fecNac, java.lang.String pasaporte, java.lang.String idioma) throws java.rmi.RemoteException;
    public java.util.Vector consultaPF_Empresario(java.lang.String cod_centro_usu, java.lang.String cod_ubic_usu, java.lang.String tipoDoc, java.lang.String numDoc, java.lang.String gen_per_corr, java.lang.String nombrePF, java.lang.String apellido1PF, java.lang.String apellido2PF, java.lang.String CIF, java.lang.String razon_social, java.lang.String idioma) throws java.rmi.RemoteException;
    public java.lang.String modificaPF(es.altia.agora.webservice.tercero.servicios.lanbide.cliente.AccesoValueObject accesoValueObject, es.altia.agora.webservice.tercero.servicios.lanbide.cliente.PersonaFisicaWSValueObject personaFisicaWSValueObject, java.lang.String idioma) throws java.rmi.RemoteException;
    public java.lang.String modificaPFNet(java.lang.String tipo_doc, java.lang.String num_doc, java.lang.String pass_dem, java.lang.String tel1, java.lang.String tel2, java.lang.String tel3, java.lang.String tel4, java.lang.String tel_notif, java.lang.String fax, java.lang.String email, java.lang.String nopais, java.lang.String noexttexto1, java.lang.String noextcodpost, java.lang.String noexttexto2, java.lang.String noprovin, java.lang.String nomuni, java.lang.String nocopos, java.lang.String notivipu, java.lang.String nonovp, java.lang.String nonuvp, java.lang.String nobisdup, java.lang.String noescale, java.lang.String nopiso, java.lang.String nolepu, java.lang.String idioma) throws java.rmi.RemoteException;
    public java.lang.String altaColectivo43(java.lang.String tipo_doc, java.lang.String num_doc, java.lang.String pass_dem, java.lang.String tel1, java.lang.String tel2, java.lang.String tel3, java.lang.String tel4, java.lang.String telNotif, java.lang.String email, java.lang.String idioma) throws java.rmi.RemoteException;
    public java.lang.String altaSimplePF(java.lang.String cod_centro_usu, java.lang.String cod_ubic_usu, java.lang.String tipo_doc, java.lang.String num_doc, java.lang.String nombre, java.lang.String ape1, java.lang.String ape2, java.lang.String SS, java.lang.String f_nac, java.lang.String sexo, java.lang.String niv_for, java.lang.String nacion, java.lang.String tel1, java.lang.String tel2, java.lang.String tel3, java.lang.String tel4, java.lang.String tel_notif, java.lang.String fax, java.lang.String email, java.lang.String repais, java.lang.String reexttexto1, java.lang.String reextcodpost, java.lang.String reexttexto2, java.lang.String renut, java.lang.String reprovin, java.lang.String remuni, java.lang.String recopos, java.lang.String retivipu, java.lang.String renovp, java.lang.String renuvp, java.lang.String rebisdup, java.lang.String reescale, java.lang.String repiso, java.lang.String relepu, java.lang.String nopais, java.lang.String noexttexto1, java.lang.String noextcodpost, java.lang.String noexttexto2, java.lang.String noprovin, java.lang.String nomuni, java.lang.String nocopos, java.lang.String notivipu, java.lang.String nonovp, java.lang.String nonuvp, java.lang.String nobisdup, java.lang.String noescale, java.lang.String nopiso, java.lang.String nolepu, java.lang.String grado_discap, java.lang.String f_ini_discap, java.lang.String f_fin_discap, java.lang.String rgi_num_exp_activ, java.lang.String tipo_autoriz, java.lang.String f_autoriz_fin_vig, java.lang.String f_autoriz_renov, java.lang.String cod_ambito_ccaa, java.lang.String cod_ambito_prov, java.lang.String cod_ambito_isla, java.lang.String cod_ambito_muni, java.lang.String cod_ambito_comarca, java.lang.String restric_activ, java.lang.String restric_ocupacion, java.lang.String idioma, java.lang.String pasaporte, java.lang.String nombreReconocido, java.lang.String ape1Reconocido, java.lang.String ape2Reconocido, java.lang.String generoReconocido, java.lang.String fecResolReconocido) throws java.rmi.RemoteException;
    public java.lang.String modificaEmpresario(java.lang.String origen, java.lang.String CIF, java.lang.String razon_social, java.lang.String nombre_comercial, java.lang.String provincia_loccont, java.lang.String municipio_loccont, java.lang.String cp_loccont, java.lang.String tipovia_loccont, java.lang.String via_loccont, java.lang.String numvia_loccont, java.lang.String bisdup_loccont, java.lang.String esc_loccont, java.lang.String piso_loccont, java.lang.String puerta_loccont, java.lang.String tlfno_loccont, java.lang.String fax_loccont, java.lang.String email_loccont, java.lang.String nombre_contacto_loccont, java.lang.String apellido1_contacto_loccont, java.lang.String apellido2_contacto_loccont, java.lang.String provincia_razsoc, java.lang.String municipio_razsoc, java.lang.String cp_razsoc, java.lang.String tipovia_razsoc, java.lang.String via_razsoc, java.lang.String numvia_razsoc, java.lang.String bisdup_razsoc, java.lang.String esc_razsoc, java.lang.String piso_razsoc, java.lang.String puerta_razsoc, java.lang.String tlfno_razsoc, java.lang.String fax_razsoc, java.lang.String email_razsoc) throws java.rmi.RemoteException;
    public java.lang.String altaEmpresarioLocal(java.lang.String origen, java.lang.String CIF, java.lang.String nombre_empresario, java.lang.String apellido1_empresario, java.lang.String apellido2_empresario, java.lang.String razon_social, java.lang.String nombre_comercial, java.lang.String tipo_empresa, java.lang.String titularidad, java.lang.String provincia_loc, java.lang.String municipio_loc, java.lang.String cp_loc, java.lang.String tipovia_loc, java.lang.String via_loc, java.lang.String numvia_loc, java.lang.String bisdup_loc, java.lang.String esc_loc, java.lang.String piso_loc, java.lang.String puerta_loc, java.lang.String tlfno_loc, java.lang.String fax_loc, java.lang.String email_loc, java.lang.String nombre_contacto_loc, java.lang.String apellido1_contacto_loc, java.lang.String apellido2_contacto_loc, java.lang.String provincia_razsoc, java.lang.String municipio_razsoc, java.lang.String cp_razsoc, java.lang.String tipovia_razsoc, java.lang.String via_razsoc, java.lang.String numvia_razsoc, java.lang.String bisdup_razsoc, java.lang.String esc_razsoc, java.lang.String piso_razsoc, java.lang.String puerta_razsoc, java.lang.String tlfno_razsoc, java.lang.String fax_razsoc, java.lang.String email_razsoc, java.lang.String nombre_contacto_razsoc, java.lang.String apellido1_contacto_razsoc, java.lang.String apellido2_contacto_razsoc, java.lang.String idioma_cvs, java.lang.String tipo_autoriz, java.lang.String fecAlta_autoriz, java.lang.String fecBaja_autoriz) throws java.rmi.RemoteException;
    public java.util.Vector obtenerStringErrores(java.util.Vector v_registros, java.lang.String proceso) throws java.rmi.RemoteException;
}
