/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantCatalogacionManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantCatalogacionValueObject;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoCatalogacionesForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoCatalogacionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Iterator;
import java.util.Collection;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class CargarCatalogacionesAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(CargarCatalogacionesAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("CargarCatalogacionesAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        if (form == null) {
            m_Log.debug("Rellenamos el form de Mantenimiento de Catalogaciones");
            form = new MantenimientoCatalogacionesForm();
            request.setAttribute(mapping.getAttribute(), form);
        }
        MantenimientoCatalogacionForm ambitoForm = null;
        Iterator catalogacionesIt = MantCatalogacionManager.getInstance().findAll(params).iterator();
        MantCatalogacionValueObject catalogacionVO = null;
        Collection catalogaciones = new ArrayList();
        while (catalogacionesIt.hasNext()) {
            catalogacionVO = (MantCatalogacionValueObject) catalogacionesIt.next();
            ambitoForm = new MantenimientoCatalogacionForm();
            ambitoForm.setCodigo(catalogacionVO.getCodigo());
            ambitoForm.setDescripcion(catalogacionVO.getDescripcion());
            catalogaciones.add(ambitoForm);
        }
        ((MantenimientoCatalogacionesForm) form).setCatalogaciones(catalogaciones);
        session.setAttribute("MantenimientoCatalogacionesForm", form);
        return (mapping.findForward("default"));
    }
}