/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantOrganoAprobacionManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantOrganoAprobacionValueObject;
import es.altia.agora.business.planeamiento.persistence.RegistroManager;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoOrganosAprobacionForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoOrganoAprobacionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Iterator;
import java.util.Collection;
import java.util.ArrayList;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarOrganoAprobacionAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarOrganoAprobacionAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("EliminarOrganoAprobacionAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        MantenimientoOrganosAprobacionForm organosAprobacionForm = (MantenimientoOrganosAprobacionForm) form;

        //Comprobamos que el organoAprobacion no esta siendo utilizado
        Vector registros = RegistroManager.getInstance().findByOrganoAprobacion(organosAprobacionForm.getCodigo(), params);
        if (!registros.isEmpty()) {
            request.setAttribute("organosAprobacion", ((MantenimientoOrganosAprobacionForm)
                session.getAttribute("MantenimientoOrganosAprobacionForm")).getOrganosAprobacion());
            return (mapping.findForward("noDelete"));
        }
        
        MantOrganoAprobacionValueObject organoAprobacionVO = new MantOrganoAprobacionValueObject(organosAprobacionForm.getCodigo(), organosAprobacionForm.getDescripcion());
        MantOrganoAprobacionManager.getInstance().delete(organoAprobacionVO, params);

        Iterator organosAprobacionIt = ((MantenimientoOrganosAprobacionForm)
                session.getAttribute("MantenimientoOrganosAprobacionForm")).getOrganosAprobacion().iterator();
        Collection organosAprobacion = new ArrayList();
        while (organosAprobacionIt.hasNext()) {
            MantenimientoOrganoAprobacionForm mantOrganoAprobacionForm = (MantenimientoOrganoAprobacionForm) organosAprobacionIt.next();
            if (!mantOrganoAprobacionForm.getCodigo().equals(organosAprobacionForm.getCodigo())) {
                organosAprobacion.add(mantOrganoAprobacionForm);
            }
        }

        organosAprobacionForm.setOrganosAprobacion(organosAprobacion);

        session.setAttribute("MantenimientoOrganosAprobacionForm", organosAprobacionForm);
        return (mapping.findForward("default"));
    }
}