/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantSubseccionManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantSubseccionValueObject;
import es.altia.agora.business.planeamiento.persistence.RegistroManager;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoSubseccionesForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoSubseccionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Iterator;
import java.util.Collection;
import java.util.ArrayList;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarSubseccionAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarSubseccionAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("EliminarSubseccionAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        MantenimientoSubseccionesForm subseccionesForm = (MantenimientoSubseccionesForm) form;

        //Comprobamos que el subseccion no esta siendo utilizado
        Vector registros = RegistroManager.getInstance().findBySubseccion(new Character(
                subseccionesForm.getTipoRegistro().charAt(0)), subseccionesForm.getCodigo(), params);
        if (!registros.isEmpty()) {
            request.setAttribute("subsecciones", ((MantenimientoSubseccionesForm)
                session.getAttribute("MantenimientoSubseccionesForm")).getSubsecciones());
            return (mapping.findForward("noDelete"));
        }
        
        MantSubseccionValueObject subseccionVO = new MantSubseccionValueObject(new Character(
                subseccionesForm.getTipoRegistro().charAt(0)), subseccionesForm.getCodigo(),
                subseccionesForm.getDescripcion());
        MantSubseccionManager.getInstance().delete(subseccionVO, params);

        Iterator subseccionesIt = ((MantenimientoSubseccionesForm)
                session.getAttribute("MantenimientoSubseccionesForm")).getSubsecciones().iterator();
        Collection subsecciones = new ArrayList();
        while (subseccionesIt.hasNext()) {
            MantenimientoSubseccionForm mantSubseccionForm = (MantenimientoSubseccionForm) subseccionesIt.next();
            if (!mantSubseccionForm.getCodigo().equals(subseccionesForm.getCodigo())) {
                subsecciones.add(mantSubseccionForm);
            }
        }

        subseccionesForm.setSubsecciones(subsecciones);

        session.setAttribute("MantenimientoSubseccionesForm", subseccionesForm);
        return (mapping.findForward("default"));
    }
}