/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantCatalogacionManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantCatalogacionValueObject;
import es.altia.agora.business.planeamiento.persistence.RegistroManager;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoCatalogacionesForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoCatalogacionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Iterator;
import java.util.Collection;
import java.util.ArrayList;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarCatalogacionAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarCatalogacionAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("EliminarCatalogacionAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        MantenimientoCatalogacionesForm catalogacionesForm = (MantenimientoCatalogacionesForm) form;

        //Comprobamos que el catalogacion no esta siendo utilizado
        Vector registros = RegistroManager.getInstance().findByCatalogacion(catalogacionesForm.getCodigo(), params);
        if (!registros.isEmpty()) {
            request.setAttribute("catalogaciones", ((MantenimientoCatalogacionesForm)
                session.getAttribute("MantenimientoCatalogacionesForm")).getCatalogaciones());
            return (mapping.findForward("noDelete"));
        }
        
        MantCatalogacionValueObject catalogacionVO = new MantCatalogacionValueObject(catalogacionesForm.getCodigo(), catalogacionesForm.getDescripcion());
        MantCatalogacionManager.getInstance().delete(catalogacionVO, params);

        Iterator catalogacionesIt = ((MantenimientoCatalogacionesForm)
                session.getAttribute("MantenimientoCatalogacionesForm")).getCatalogaciones().iterator();
        Collection catalogaciones = new ArrayList();
        while (catalogacionesIt.hasNext()) {
            MantenimientoCatalogacionForm mantCatalogacionForm = (MantenimientoCatalogacionForm) catalogacionesIt.next();
            if (!mantCatalogacionForm.getCodigo().equals(catalogacionesForm.getCodigo())) {
                catalogaciones.add(mantCatalogacionForm);
            }
        }

        catalogacionesForm.setCatalogaciones(catalogaciones);

        session.setAttribute("MantenimientoCatalogacionesForm", catalogacionesForm);
        return (mapping.findForward("default"));
    }
}