/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantTipoManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantTipoValueObject;
import es.altia.agora.business.planeamiento.persistence.RegistroManager;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoTiposForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoTipoForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Iterator;
import java.util.Collection;
import java.util.ArrayList;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarTipoAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarTipoAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("EliminarTipoAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        MantenimientoTiposForm tiposForm = (MantenimientoTiposForm) form;

        //Comprobamos que el tipo no esta siendo utilizado
        Vector registros = RegistroManager.getInstance().findByTipo(new Character(
                tiposForm.getTipoRegistro().charAt(0)), tiposForm.getCodigoSubseccion(), tiposForm.getCodigo(), params);
        if (!registros.isEmpty()) {
            Iterator tiposIt = ((MantenimientoTiposForm)
                session.getAttribute("MantenimientoTiposForm")).getTipos().iterator();
            while (tiposIt.hasNext()) {
                m_Log.debug((MantenimientoTipoForm) tiposIt.next());
            }
            request.setAttribute("tipos", ((MantenimientoTiposForm)
                    session.getAttribute("MantenimientoTiposForm")).getTipos());
            return (mapping.findForward("noDelete"));
        }
        
        MantTipoValueObject tipoVO = new MantTipoValueObject(new Character(
                tiposForm.getTipoRegistro().charAt(0)), tiposForm.getCodigoSubseccion(), tiposForm.getCodigo(),
                tiposForm.getDescripcion());
        MantTipoManager.getInstance().delete(tipoVO, params);

        Iterator tiposIt = ((MantenimientoTiposForm)
                session.getAttribute("MantenimientoTiposForm")).getTipos().iterator();
        Collection tipos = new ArrayList();
        while (tiposIt.hasNext()) {
            MantenimientoTipoForm mantTipoForm = (MantenimientoTipoForm) tiposIt.next();
            if (!mantTipoForm.getCodigoSubseccion().equals(tiposForm.getCodigoSubseccion()) ||
                    !mantTipoForm.getCodigo().equals(tiposForm.getCodigo())) {
                tipos.add(mantTipoForm);
            }
        }

        tiposForm.setTipos(tipos);

        session.setAttribute("MantenimientoTiposForm", tiposForm);
        return (mapping.findForward("default"));
    }
}