/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.MantSubseccionManager;
import es.altia.agora.business.planeamiento.mantenimiento.MantSubseccionValueObject;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoSubseccionesForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.mantenimiento.MantenimientoSubseccionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Collection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class InsertarSubseccionAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(InsertarSubseccionAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("InsertarSubseccionAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        MantenimientoSubseccionesForm subseccionesForm = (MantenimientoSubseccionesForm) form;
        MantSubseccionValueObject subseccionVO = new MantSubseccionValueObject(new Character(
                subseccionesForm.getTipoRegistro().charAt(0)), subseccionesForm.getCodigo(),
                subseccionesForm.getDescripcion());
        MantSubseccionManager.getInstance().create(subseccionVO, params);

        Collection subsecciones = ((MantenimientoSubseccionesForm)
                session.getAttribute("MantenimientoSubseccionesForm")).getSubsecciones();
        MantenimientoSubseccionForm subseccionForm = new MantenimientoSubseccionForm();
        subseccionForm.setTipoRegistro(subseccionesForm.getTipoRegistro());
        subseccionForm.setCodigo(subseccionesForm.getCodigo());
        subseccionForm.setDescripcion(subseccionesForm.getDescripcion());
        subsecciones.add(subseccionForm);
        subseccionesForm.setSubsecciones(subsecciones);

        session.setAttribute("MantenimientoSubseccionesForm", subseccionesForm);
        return (mapping.findForward("default"));
    }
}