/* Generated by Together */ 
package es.altia.agora.interfaces.user.web.informes;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.registro.exception.AnotacionRegistroException;
import es.altia.agora.business.geninformes.GeneradorInformesValueObject;
import es.altia.agora.business.geninformes.persistence.GeneradorInformesManager;
import es.altia.agora.interfaces.user.web.helper.ActionHelper;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.common.service.config.*;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

  public final class GeneradorInformesAction extends ActionSession {

  protected static Log m_Log =
          LogFactory.getLog(GeneradorInformesAction.class.getName());
      
  protected static Config m_Conf = ConfigServiceHelper.getConfig("common");

      public ActionForward performSession(	ActionMapping mapping,
                  ActionForm form,
                  HttpServletRequest request,
                  HttpServletResponse response) throws IOException, ServletException {

    m_Log.debug("perform");
    ActionHelper myActionHelper = new ActionHelper(getLocale(request), getResources(request));


          // Validaremos los parametros del request especificados
    HttpSession session = request.getSession();
    String opcion ="";

    if ((session.getAttribute("usuario") != null)) {
      UsuarioValueObject usuario = (UsuarioValueObject)session.getAttribute("usuario");
      String[] params = usuario.getParamsCon();
      int cod_dep;
      int cod_uni;
      cod_dep= usuario.getDepCod();
      cod_uni= usuario.getUnidadOrgCod();

      // Si usuario en sesion es nulo --> error.

      ActionErrors errors = new ActionErrors();

      GeneradorInformesValueObject genInfVO = new GeneradorInformesValueObject();
      GeneradorInformesForm genInfForm = null;
      
      if (form == null) {
        m_Log.debug("Rellenamos el form de Generador de Informes");
        form = new GeneradorInformesForm();
        if ("request".equals(mapping.getScope()))
          request.setAttribute(mapping.getAttribute(), form);
        else
          session.setAttribute(mapping.getAttribute(), form);
      }

      genInfForm = (GeneradorInformesForm)form;

      opcion = request.getParameter("opcion");
      if (m_Log.isInfoEnabled()) m_Log.info("la opcion en el action es " + opcion);

	    if (opcion.equals("inicio")){
				String codAplicacion = request.getParameter("operacion");
				Vector listaEntidades = GeneradorInformesManager.getInstance().getListaEntidades(codAplicacion,params);
				genInfVO.setListaEntidades(listaEntidades);
				genInfVO.setCodAplicacion(codAplicacion);
				String operacion = "alta";
	    	genInfVO.setOperacion(operacion);
	      
	      genInfForm.setGeneradorInformes(genInfVO);
	      opcion = "inicio";
	    } else if(opcion.equals("cargarCamposDisponibles")) {
	    	String codEntidad = request.getParameter("codEntidad");
	    	Vector listaCamposDisponibles = GeneradorInformesManager.getInstance().getListaCampos(codEntidad,params);
	    	genInfVO.setListaCamposDisponibles(listaCamposDisponibles);
	    	String operacion = "cargarCamposDisponibles";
	    	genInfVO.setOperacion("operacion");
	    	
	    	genInfForm.setGeneradorInformes(genInfVO);
	      opcion = "cargarCamposDisponibles";
	    } else if(opcion.equals("altaInforme")) {
	    	GeneralValueObject gVO = new GeneralValueObject();
	    	gVO = obtenerParametros(gVO,request);
	    	String consultaSQL = crearConsultaSQL(gVO,params);
	    	gVO.setAtributo("consultaSQL",consultaSQL);
	    	int resultado = GeneradorInformesManager.getInstance().altaInforme(gVO,params);
	    	genInfVO.setListaCamposDisponibles(new Vector());
	    	String operacion = "";
	    	if(resultado >0) {
	    		operacion = "altaCorrecta";
	    	} else {
	    		operacion = "altaIncorrecta";
	    	}
	    	genInfVO.setOperacion(operacion);
	    	genInfForm.setGeneradorInformes(genInfVO);
	      opcion = "altaInforme";
	    } else if(opcion.equals("recuperarInforme")) {
				GeneralValueObject gVO = new GeneralValueObject();
	    	String codAplicacion = request.getParameter("operacion");
	    	gVO.setAtributo("codAplicacion",codAplicacion);
	    	genInfVO.setCodAplicacion(codAplicacion);
				Vector listaEntidades = GeneradorInformesManager.getInstance().getListaEntidades(codAplicacion,params);
				genInfVO.setListaEntidades(listaEntidades);
	    	String codInforme = request.getParameter("tipoFichero");
	    	gVO.setAtributo("codInforme",codInforme);
	    	gVO = GeneradorInformesManager.getInstance().obtenerInforme(gVO,params);
	    	genInfVO.setGVO(gVO);
	    	String operacion = "modificar";
	    	genInfVO.setOperacion(operacion);
	    	genInfForm.setGeneradorInformes(genInfVO);
	      opcion = "recuperarInforme";
	    } else if(opcion.equals("modificarInforme")) {
	    	GeneralValueObject gVO = new GeneralValueObject();
	    	String codEstructura = request.getParameter("codEstructura");
				String codInforme = request.getParameter("codInforme");
				gVO.setAtributo("codEstructura",codEstructura);
				gVO.setAtributo("codInforme",codInforme);
	    	gVO = obtenerParametros(gVO,request);
	    	String consultaSQL = crearConsultaSQL(gVO,params);
	    	gVO.setAtributo("consultaSQL",consultaSQL);
	    	int resultado = GeneradorInformesManager.getInstance().modificarInforme(gVO,params);
	    	genInfVO.setListaCamposDisponibles(new Vector());
	    	String operacion = "";
	    	if(resultado >0) {
	    		operacion = "modificacionCorrecta";
	    	} else {
	    		operacion = "modificacionIncorrecta";
	    	}
	    	genInfVO.setOperacion(operacion);
	    	genInfForm.setGeneradorInformes(genInfVO);
	      opcion = "modificarInforme";
	    }

 } else { // No hay usuario.
            m_Log.debug("MantAnotacionRegistroAction --> no hay usuario");
            opcion = "no_usuario";
 }

  /* Redirigimos al JSP de salida*/
      return (mapping.findForward(opcion));

}

private String crearConsultaSQL(GeneralValueObject gVO,String[] params) {
  String sql = "";
  String codEntidad = (String)gVO.getAtributo("codEntidad");
  String nombreVista = "";
  try {
    nombreVista = GeneradorInformesManager.getInstance().getNombreVista(codEntidad,params);
  } catch (AnotacionRegistroException e) {
      m_Log.error("ERROR en getNombreVista en el action");
  }
  gVO.setAtributo("nombreVista",nombreVista);
  
  sql = "SELECT ";
  Vector listaCampoCampos = new Vector();
  listaCampoCampos = (Vector) gVO.getAtributo("listaCampoCampos");
  Vector listaNombreAs = new Vector();
  listaNombreAs = (Vector) gVO.getAtributo("listaNombreAs");
  for(int i=0;i<listaCampoCampos.size();i++) {
    sql += listaCampoCampos.elementAt(i) + " AS " + listaNombreAs.elementAt(i) + ",";	
  }
  sql = sql.substring(0,sql.length()-1);
  sql += " FROM " + nombreVista + " WHERE ";
  Vector listaCodCamposElegidos = new Vector();
  listaCodCamposElegidos = (Vector) gVO.getAtributo("listaCodCamposElegidos");
  String codCampo1 = (String) gVO.getAtributo("codCampo1");
  String codCampo2 = (String) gVO.getAtributo("codCampo2");
  String codCampo3 = (String) gVO.getAtributo("codCampo3");
  String codCampo4 = (String) gVO.getAtributo("codCampo4");
  String codCampo5 = (String) gVO.getAtributo("codCampo5");
  String codCampo6 = (String) gVO.getAtributo("codCampo6");
  String codCampo7 = (String) gVO.getAtributo("codCampo7");
  String codCondicion1 = (String) gVO.getAtributo("codCondicion1");
  String codCondicion2 = (String) gVO.getAtributo("codCondicion2");
  String codCondicion3 = (String) gVO.getAtributo("codCondicion3");
  String codCondicion4 = (String) gVO.getAtributo("codCondicion4");
  String codCondicion5 = (String) gVO.getAtributo("codCondicion5");
  String codCondicion6 = (String) gVO.getAtributo("codCondicion6");
  String codCondicion7 = (String) gVO.getAtributo("codCondicion7");
  String valor1 = (String) gVO.getAtributo("valor1");
  String valor2 = (String) gVO.getAtributo("valor2");
  String valor3 = (String) gVO.getAtributo("valor3");
  String valor4 = (String) gVO.getAtributo("valor4");
  String valor5 = (String) gVO.getAtributo("valor5");
  String valor6 = (String) gVO.getAtributo("valor6");
  String valor7 = (String) gVO.getAtributo("valor7");
  String codOperador1 = (String) gVO.getAtributo("codOperador1");
  String codOperador2 = (String) gVO.getAtributo("codOperador2");
  String codOperador3 = (String) gVO.getAtributo("codOperador3");
  String codOperador4 = (String) gVO.getAtributo("codOperador4");
  String codOperador5 = (String) gVO.getAtributo("codOperador5");
  String codOperador6 = (String) gVO.getAtributo("codOperador6");
  
  Vector listaCamposDisponiblesEnteros = new Vector();
  try {
    listaCamposDisponiblesEnteros = GeneradorInformesManager.getInstance().listaCamposDisponiblesEnteros(codEntidad,params);
  } catch (AnotacionRegistroException e) {
      m_Log.error("ERROR en getNombreVista en el action");
  }
  
  for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
  	GeneralValueObject g = new GeneralValueObject();
  	g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  	String codCampoDisponible = (String) g.getAtributo("codCampo");
  	String campoDisponible = (String) g.getAtributo("campo");
  	if(codCampo1.equals(codCampoDisponible)) {
  		sql += campoDisponible + " " + codCondicion1 + " ";
  		if(!"IS NULL".equals(codCondicion1) && !"IS NOT NULL".equals(codCondicion1)) {
  			sql += "'" + valor1 + "'";
  		}
  		break;
  	}
  }
  if(!"".equals(codOperador1)) {
		sql += " " + codOperador1 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo2.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion2 + " ";
	  		if(!"IS NULL".equals(codCondicion2) && !"IS NOT NULL".equals(codCondicion2)) {
  			  sql += "'" + valor2 + "'";
  		  }
	  		break;
	  	}
    }
	}
	if(!"".equals(codOperador2)) {
		sql += " " + codOperador2 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo3.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion3 + " ";
	  		if(!"IS NULL".equals(codCondicion3) && !"IS NOT NULL".equals(codCondicion3)) {
  			  sql += "'" + valor3 + "'";
  		  }
	  		break;
	  	}
    }
	}
	if(!"".equals(codOperador3)) {
		sql += " " + codOperador3 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo4.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion4 + " ";
	  		if(!"IS NULL".equals(codCondicion4) && !"IS NOT NULL".equals(codCondicion4)) {
  			  sql += "'" + valor4 + "'";
  		  }
	  		break;
	  	}
    }
	}
	if(!"".equals(codOperador4)) {
		sql += " " + codOperador4 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo5.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion5 + " ";
	  		if(!"IS NULL".equals(codCondicion5) && !"IS NOT NULL".equals(codCondicion5)) {
  			  sql += "'" + valor5 + "'";
  		  }
	  		break;
	  	}
    }
	}
	if(!"".equals(codOperador5)) {
		sql += " " + codOperador5 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo6.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion6 + " ";
	  		if(!"IS NULL".equals(codCondicion6) && !"IS NOT NULL".equals(codCondicion6)) {
  			  sql += "'" + valor6 + "'";
  		  }
	  		break;
	  	}
    }
	}
	if(!"".equals(codOperador6)) {
		sql += " " + codOperador6 + " ";
		for(int j=0;j<listaCamposDisponiblesEnteros.size();j++) {
			GeneralValueObject g = new GeneralValueObject();
  		g = (GeneralValueObject) listaCamposDisponiblesEnteros.elementAt(j);
  		String codCampoDisponible = (String) g.getAtributo("codCampo");
  		String campoDisponible = (String) g.getAtributo("campo");
			if(codCampo7.equals(codCampoDisponible)) {
	  		sql += campoDisponible + " " + codCondicion7 + " ";
	  		if(!"IS NULL".equals(codCondicion7) && !"IS NOT NULL".equals(codCondicion7)) {
  			  sql += "'" + valor7 + "'";
  		  }
	  		break;
	  	}
    }
	}
	
	String codCampoOrdenacion1 = (String) gVO.getAtributo("codCampoOrdenacion1");
	String codCampoOrdenacion2 = (String) gVO.getAtributo("codCampoOrdenacion2");
	String codCampoOrdenacion3 = (String) gVO.getAtributo("codCampoOrdenacion3");
	String codCampoOrdenacion4 = (String) gVO.getAtributo("codCampoOrdenacion4");
	String codCampoOrdenacion5 = (String) gVO.getAtributo("codCampoOrdenacion5");
	String codSentidoOrdenacion1 = (String) gVO.getAtributo("codSentidoOrdenacion1");
	String codSentidoOrdenacion2 = (String) gVO.getAtributo("codSentidoOrdenacion2");
	String codSentidoOrdenacion3 = (String) gVO.getAtributo("codSentidoOrdenacion3");
	String codSentidoOrdenacion4 = (String) gVO.getAtributo("codSentidoOrdenacion4");
	String codSentidoOrdenacion5 = (String) gVO.getAtributo("codSentidoOrdenacion5");
	
	if(!"".equals(codCampoOrdenacion1)) {
		for(int j=0;j<listaCodCamposElegidos.size();j++) {
			if(codCampoOrdenacion1.equals(listaCodCamposElegidos.elementAt(j))) {
	  		sql += " ORDER BY " + listaCampoCampos.elementAt(j) + " " + codSentidoOrdenacion1 + " ";
	  		break;
	  	}
    }
	}
	if(!"".equals(codCampoOrdenacion2)) {
		for(int j=0;j<listaCodCamposElegidos.size();j++) {
			if(codCampoOrdenacion2.equals(listaCodCamposElegidos.elementAt(j))) {
	  		sql += "," + listaCampoCampos.elementAt(j) + " " + codSentidoOrdenacion2 + " ";
	  		break;
	  	}
    }
	}
	if(!"".equals(codCampoOrdenacion3)) {
		for(int j=0;j<listaCodCamposElegidos.size();j++) {
			if(codCampoOrdenacion3.equals(listaCodCamposElegidos.elementAt(j))) {
	  		sql += "," + listaCampoCampos.elementAt(j) + " " + codSentidoOrdenacion3 + " ";
	  		break;
	  	}
    }
	}
	if(!"".equals(codCampoOrdenacion4)) {
		for(int j=0;j<listaCodCamposElegidos.size();j++) {
			if(codCampoOrdenacion4.equals(listaCodCamposElegidos.elementAt(j))) {
	  		sql += "," + listaCampoCampos.elementAt(j) + " " + codSentidoOrdenacion4 + " ";
	  		break;
	  	}
    }
	}
	if(!"".equals(codCampoOrdenacion5)) {
		for(int j=0;j<listaCodCamposElegidos.size();j++) {
			if(codCampoOrdenacion5.equals(listaCodCamposElegidos.elementAt(j))) {
	  		sql += "," + listaCampoCampos.elementAt(j) + " " + codSentidoOrdenacion5 + " ";
	  		break;
	  	}
    }
	}
	if(m_Log.isDebugEnabled()) m_Log.debug("la consultaSQL es : " + sql);
  return sql;	
}

private GeneralValueObject obtenerParametros(GeneralValueObject gVO,HttpServletRequest request) {
	String descEntidad = request.getParameter("descEntidad");
	String codAplicacion = request.getParameter("codAplicacion");
	String nombreInforme = request.getParameter("nombreInforme");
	String descInforme = request.getParameter("descripcion");
	String codEntidad = request.getParameter("codEntidad");
	String listaCodCamposElegidos = request.getParameter("listaCodCamposElegidos");
	String listaCampoCampos = request.getParameter("listaCampoCampos");
	String listaNombreAs = request.getParameter("listaNombreAs");
	String codCampoOrdenacion1 = request.getParameter("codCampoOrdenacion1");
	String codCampoOrdenacion2 = request.getParameter("codCampoOrdenacion2");
	String codCampoOrdenacion3 = request.getParameter("codCampoOrdenacion3");
	String codCampoOrdenacion4 = request.getParameter("codCampoOrdenacion4");
	String codCampoOrdenacion5 = request.getParameter("codCampoOrdenacion5");
	String codSentidoOrdenacion1 = request.getParameter("codSentidoOrdenacion1");
	String codSentidoOrdenacion2 = request.getParameter("codSentidoOrdenacion2");
	String codSentidoOrdenacion3 = request.getParameter("codSentidoOrdenacion3");
	String codSentidoOrdenacion4 = request.getParameter("codSentidoOrdenacion4");
	String codSentidoOrdenacion5 = request.getParameter("codSentidoOrdenacion5");
	String codOperador1 = request.getParameter("codOperador1");
	String codOperador2 = request.getParameter("codOperador2");
	String codOperador3 = request.getParameter("codOperador3");
	String codOperador4 = request.getParameter("codOperador4");
	String codOperador5 = request.getParameter("codOperador5");
	String codOperador6 = request.getParameter("codOperador6");
	String codCampo1 = request.getParameter("codCampo1");
	String codCampo2 = request.getParameter("codCampo2");
	String codCampo3 = request.getParameter("codCampo3");
	String codCampo4 = request.getParameter("codCampo4");
	String codCampo5 = request.getParameter("codCampo5");
	String codCampo6 = request.getParameter("codCampo6");
	String codCampo7 = request.getParameter("codCampo7");
	String codCondicion1 = request.getParameter("codCondicion1");
	String codCondicion2 = request.getParameter("codCondicion2");
	String codCondicion3 = request.getParameter("codCondicion3");
	String codCondicion4 = request.getParameter("codCondicion4");
	String codCondicion5 = request.getParameter("codCondicion5");
	String codCondicion6 = request.getParameter("codCondicion6");
	String codCondicion7 = request.getParameter("codCondicion7");
	String valor1 = request.getParameter("valor1");
	String valor2 = request.getParameter("valor2");
	String valor3 = request.getParameter("valor3");
	String valor4 = request.getParameter("valor4");
	String valor5 = request.getParameter("valor5");
	String valor6 = request.getParameter("valor6");
	String valor7 = request.getParameter("valor7");
	
	gVO.setAtributo("descEntidad",descEntidad);
	gVO.setAtributo("codAplicacion",codAplicacion);
	gVO.setAtributo("nombreInforme",nombreInforme);
	gVO.setAtributo("descInforme",descInforme);
	gVO.setAtributo("codEntidad",codEntidad);
	gVO.setAtributo("listaCodCamposElegidos",listaTemasSeleccionados(listaCodCamposElegidos));
	gVO.setAtributo("listaCampoCampos",listaTemasSeleccionados(listaCampoCampos));
	gVO.setAtributo("listaNombreAs",listaTemasSeleccionados(listaNombreAs));
	gVO.setAtributo("codCampoOrdenacion1",codCampoOrdenacion1);
	gVO.setAtributo("codCampoOrdenacion2",codCampoOrdenacion2);
	gVO.setAtributo("codCampoOrdenacion3",codCampoOrdenacion3);
	gVO.setAtributo("codCampoOrdenacion4",codCampoOrdenacion4);
	gVO.setAtributo("codCampoOrdenacion5",codCampoOrdenacion5);
	gVO.setAtributo("codSentidoOrdenacion1",codSentidoOrdenacion1);
	gVO.setAtributo("codSentidoOrdenacion2",codSentidoOrdenacion2);
	gVO.setAtributo("codSentidoOrdenacion3",codSentidoOrdenacion3);
	gVO.setAtributo("codSentidoOrdenacion4",codSentidoOrdenacion4);
	gVO.setAtributo("codSentidoOrdenacion5",codSentidoOrdenacion5);
	gVO.setAtributo("codOperador1",codOperador1);
	gVO.setAtributo("codOperador2",codOperador2);
	gVO.setAtributo("codOperador3",codOperador3);
	gVO.setAtributo("codOperador4",codOperador4);
	gVO.setAtributo("codOperador5",codOperador5);
	gVO.setAtributo("codOperador6",codOperador6);
	gVO.setAtributo("codCampo1",codCampo1);
	gVO.setAtributo("codCampo2",codCampo2);
	gVO.setAtributo("codCampo3",codCampo3);
	gVO.setAtributo("codCampo4",codCampo4);
	gVO.setAtributo("codCampo5",codCampo5);
	gVO.setAtributo("codCampo6",codCampo6);
	gVO.setAtributo("codCampo7",codCampo7);
	gVO.setAtributo("codCondicion1",codCondicion1);
	gVO.setAtributo("codCondicion2",codCondicion2);
	gVO.setAtributo("codCondicion3",codCondicion3);
	gVO.setAtributo("codCondicion4",codCondicion4);
	gVO.setAtributo("codCondicion5",codCondicion5);
	gVO.setAtributo("codCondicion6",codCondicion6);
	gVO.setAtributo("codCondicion7",codCondicion7);
	gVO.setAtributo("valor1",valor1);
	gVO.setAtributo("valor2",valor2);
	gVO.setAtributo("valor3",valor3);
	gVO.setAtributo("valor4",valor4);
	gVO.setAtributo("valor5",valor5);
	gVO.setAtributo("valor6",valor6);
	gVO.setAtributo("valor7",valor7);
	return gVO;
}


private Vector listaTemasSeleccionados(String listTemasSelecc) {
  Vector lista = new Vector();
  StringTokenizer valores = null;
  if (listTemasSelecc != null) {
    valores = new StringTokenizer(listTemasSelecc,"зе",false);
    while (valores.hasMoreTokens()) {
      String valor = valores.nextToken();
      lista.addElement(valor);
    }
  }
  return lista;
}


}