/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.planeamiento.mantenimiento.persistence.*;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.BienAndEspacioCatalogadoForm;
import es.altia.common.service.config.Config;
import es.altia.common.service.config.ConfigServiceHelper;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Collection;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class CargarBienAndEspacioCatalogadoAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(CargarBienAndEspacioCatalogadoAction.class.getName());
    protected static Config m_ConfigTechnical = ConfigServiceHelper.getConfig("techserver");

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("CargarBienAndEspacioCatalogadoAction.perform");
        String[] params = null;
        HttpSession session = request.getSession();

        if (session.getAttribute("usuario") != null){
            UsuarioValueObject usuarioVO = (UsuarioValueObject)session.getAttribute("usuario");
            params = usuarioVO.getParamsCon();
        }

        if (form == null) {
            m_Log.debug("Rellenamos el form de BienAndEspacioCatalogado");
            form = new BienAndEspacioCatalogadoForm();
            request.setAttribute(mapping.getAttribute(), form);
        }

        Character tipoRegistro = new Character(request.getParameter("tipoRegistro").charAt(0));
        ((BienAndEspacioCatalogadoForm) form).setTipoRegistro(request.getParameter("tipoRegistro"));
        Collection catalogaciones = MantCatalogacionManager.getInstance().findAll(params);
        ((BienAndEspacioCatalogadoForm) form).setCatalogaciones(catalogaciones);
        Collection gradosProteccion = MantGradoProteccionManager.getInstance().findAll(params);
        ((BienAndEspacioCatalogadoForm) form).setGradosProteccion(gradosProteccion);
        Collection relacionesBien = MantRelacionBienManager.getInstance().findAll(params);
        ((BienAndEspacioCatalogadoForm) form).setRelacionesBien(relacionesBien);
        ((BienAndEspacioCatalogadoForm) form).setAnotaciones(new ArrayList());
        ((BienAndEspacioCatalogadoForm) form).setRectificaciones(new ArrayList());

        session.setAttribute("BienAndEspacioCatalogadoForm", form);
        if (session.getAttribute("registrosBien")!=null) {
            session.removeAttribute("registrosBien");
        }

        //Chapucilla para permitir solo consultas sin modificacion
        String consultando = request.getParameter("consultando");
        if (consultando!=null && consultando.equals("true")) {
            session.setAttribute("modoConsulta", "true");
        } else {
            session.setAttribute("modoConsulta", "false");
        }

        return (mapping.findForward("default"));
    }
}