/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action;

import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.ConvenioUrbanisticoForm;
import es.altia.agora.interfaces.user.web.planeamiento.form.AnotacionForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.util.Collection;
import java.util.Iterator;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class EliminarAnotacionConvenioAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(EliminarAnotacionConvenioAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("EliminarAnotacionConvenioAction.perform");
        HttpSession session = request.getSession();

        ConvenioUrbanisticoForm convenioForm = (ConvenioUrbanisticoForm)
                session.getAttribute("ConvenioUrbanisticoForm");
        Collection anotaciones = new ArrayList();
        Iterator anotacionesIt = convenioForm.getAnotaciones().iterator();
        AnotacionForm anotacionForm = (AnotacionForm) form;
        AnotacionForm anotForm = null;
        String numero = null;
        while (anotacionesIt.hasNext()) {
            anotForm = (AnotacionForm) anotacionesIt.next();
            if (anotForm.getNumeroAnotacion().equals(anotacionForm.getNumeroAnotacion())) {
                numero = anotForm.getNumeroAnotacion();
                break;
            }
            anotaciones.add(anotForm);
        }
        String auxnum = null;
        //Reasignamos numeros a los posteriores
        while (anotacionesIt.hasNext()) {
            anotForm = (AnotacionForm) anotacionesIt.next();
            auxnum = anotForm.getNumeroAnotacion();
            anotForm.setNumeroAnotacion(numero);
            numero = auxnum;
            anotaciones.add(anotForm);
        }

        convenioForm.setAnotaciones(anotaciones);
        session.setAttribute("ConvenioUrbanisticoForm", convenioForm);

        return (mapping.findForward("default"));
    }
}