/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import es.altia.agora.interfaces.user.web.planeamiento.form.ConvenioUrbanisticoForm;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;

import java.util.*;
import java.io.File;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import es.altia.agora.business.util.GeneralValueObject;
import es.altia.common.service.config.*;
import es.altia.util.sqlxmlpdf.GeneralPDF;
import es.altia.util.struts.StrutsUtilOperations;

public final class ImprimirConvenioUrbanisticoAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(ImprimirConvenioUrbanisticoAction.class.getName());
    protected static Config m_Conf = ConfigServiceHelper.getConfig("common");

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.debug("ImprimirConvenioUrbanisticoAction.perform");

        // Validaremos los parametros del request especificados
        HttpSession session = request.getSession();

        if ((session.getAttribute("usuario") != null)) {
            UsuarioValueObject usuario = (UsuarioValueObject)session.getAttribute("usuario");
            String[] params = usuario.getParamsCon();

            Collection registrosConvenio = (Collection) session.getAttribute("registrosConvenio");
            String idioma = request.getParameter("idioma");
            if (idioma.equals("1")) {
                idioma = "es";
            } else if (idioma.equals("2")) {
                idioma = "gl";
            }

            GeneralValueObject gVO = new GeneralValueObject();
            gVO.setAtributo("baseDir", m_Conf.getString("PDF.base_dir"));
            gVO.setAtributo("aplPathReal", this.getServlet().getServletContext().getRealPath(""));
            gVO.setAtributo("usuDir", usuario.getDtr());
            gVO.setAtributo("pdfFile", "PLANEAMIENTO");
            String protocolo = StrutsUtilOperations.getProtocol(request);                
            m_Log.debug("PROTOCOLO en uso :" + protocolo);
            gVO.setAtributo("estilo", "css/listadoPlaneamiento.css");
            GeneralPDF pdf = new GeneralPDF(params, gVO);
            File cabecera = pdf.transformaXML("<CABECERA></CABECERA>","cabeceraListadoPlaneamiento");
            gVO.setAtributo("cabecera",cabecera.getPath());
            gVO.setAtributo("tamCabecera","10mm");
            pdf = new GeneralPDF(params, gVO);

            Vector ficheros = new Vector();
            pdf = new GeneralPDF(params, gVO);
            String plantilla = "listadoConvenio";
            plantilla += "_"+idioma; // Idioma
            String textoXML = crearXML(registrosConvenio, (HashMap) session.getAttribute("criteriosConvenio"));
            m_Log.debug(textoXML);
            pdf = new GeneralPDF(params, gVO);
            ficheros.add(pdf.transformaXML(textoXML, plantilla));
            request.setAttribute("nombre", pdf.getPdf(ficheros));
        }
        /* Redirigimos al JSP de salida*/
        return (mapping.findForward("default"));
    }


    private String crearXML(Collection registrosConvenio, HashMap criterios) {

        StringBuffer textoXml = new StringBuffer("");
        textoXml.append("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>");
        textoXml.append("<LISTADO>");
        // CRITERIOS
        if (!criterios.isEmpty()) {
            textoXml.append("<CRITERIOS>");
            Iterator criteriosKeysIt = criterios.keySet().iterator();
            String key;
            String value = null;
            while (criteriosKeysIt.hasNext()) {
                key = (String) criteriosKeysIt.next();
                textoXml.append("<" + key + ">");
                value = (String) criterios.get(key);
                if (value!=null) {
                    textoXml.append(value);
                }
                textoXml.append("</" + key + ">");
            }
            textoXml.append("</CRITERIOS>");
        }
        // LISTADO
        Iterator registrosConvenioIt = registrosConvenio.iterator();
        ConvenioUrbanisticoForm convenioForm = null;
        while (registrosConvenioIt.hasNext()) {
            convenioForm = (ConvenioUrbanisticoForm) registrosConvenioIt.next();
            textoXml.append("<REGISTRO>");
            textoXml.append("<NUMERO>");
            textoXml.append(convenioForm.getAnho() + "/" + convenioForm.getNumero());
            textoXml.append("</NUMERO>");
            if (criterios.get("fechaAprobacion")==null) {
                textoXml.append("<FECHA_APROBACION>");
                textoXml.append(convenioForm.getFechaAprobacion());
                textoXml.append("</FECHA_APROBACION>");
            }
            if (criterios.get("subseccion")==null) {
                textoXml.append("<SUBSECCION>");
                textoXml.append(convenioForm.getSubseccion());
                textoXml.append("</SUBSECCION>");
            }
            if (criterios.get("objetoConvenio")==null) {
                textoXml.append("<OBJETO_CONVENIO>");
                textoXml.append(convenioForm.getObjetoConvenio().replaceAll("@intro", "\r\n"));
                textoXml.append("</OBJETO_CONVENIO>");
            }
            if (criterios.get("ambito")==null) {
                textoXml.append("<AMBITO>");
                textoXml.append(convenioForm.getAmbito());
                textoXml.append("</AMBITO>");
                String parcela = "";
                if (convenioForm.getParcela()!=null) {
                    parcela = convenioForm.getParcela();
                }
                textoXml.append("<PARCELA>");
                textoXml.append(parcela);
                textoXml.append("</PARCELA>");
            } else {
                if (criterios.get("parcela")==null) {
                    textoXml.append("<PARCELA>");
                    textoXml.append(convenioForm.getParcela());
                    textoXml.append("</PARCELA>");
                }
            }
            textoXml.append("</REGISTRO>");

        }
        textoXml.append("</LISTADO>");
        m_Log.debug(textoXml.toString());
        return textoXml.toString();
    }
}
