/* Generated by Together */
package es.altia.agora.interfaces.user.web.sge;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.sge.DefinicionAgrupacionCamposValueObject;
import es.altia.agora.business.sge.DefinicionCampoValueObject;
import es.altia.agora.business.sge.persistence.DefinicionProcedimientosManager;
import es.altia.agora.business.sge.persistence.manual.DatosSuplementariosDAO;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.agora.interfaces.user.web.helper.ActionHelper;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;
import java.io.PrintWriter;

import java.util.StringTokenizer;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

  public final class DefinicionCampoAction extends ActionSession {

  protected static Log m_Log =
          LogFactory.getLog(DefinicionCampoAction.class.getName());

      public ActionForward performSession(	ActionMapping mapping,
                  ActionForm form,
                  HttpServletRequest request,
                  HttpServletResponse response) throws IOException, ServletException {

    m_Log.debug("perform");
    ActionHelper myActionHelper = new ActionHelper(getLocale(request), getResources(request));


          // Validaremos los parametros del request especificados
    HttpSession session = request.getSession();
    String opcion ="";
    GeneralValueObject gVO = new GeneralValueObject();

    if ((session.getAttribute("usuario") != null)) {
        UsuarioValueObject usuario = (UsuarioValueObject)session.getAttribute("usuario");
        String[] params = usuario.getParamsCon();
        int cod_dep;
        int cod_uni;
        cod_dep= usuario.getDepCod();
        cod_uni= usuario.getUnidadOrgCod();

        // Si usuario en sesion es nulo --> error.
        ActionErrors errors = new ActionErrors();
        DefinicionCampoValueObject defCampoVO = new DefinicionCampoValueObject();      
        DefinicionCampoForm defCampoForm = null;

        if (form == null) {
            m_Log.debug("Rellenamos el form de Definicion de Campo");
            form = new DefinicionCampoForm();
            if ("request".equals(mapping.getScope()))
              request.setAttribute(mapping.getAttribute(), form);
            else
              session.setAttribute(mapping.getAttribute(), form);
        }

        defCampoForm = (DefinicionCampoForm)form;
        opcion = request.getParameter("opcion");
        if (m_Log.isInfoEnabled()) m_Log.info("la opcion en el action es " + opcion);

        String[] paramsDiputacion = new String[7];

        if (opcion.equals("inicio"))
        {
            String modoInicio = request.getParameter("nCS");
            String lectura = request.getParameter("lectura");            

            if("modificarDesdeProcedimiento".equals(modoInicio) || "modificarDesdeTramite".equals(modoInicio)) 
            {
                String codCampo = request.getParameter("codMun");
                String descCampo = request.getParameter("codProc");
                String codPlantilla = request.getParameter("codTram");
                String codTipoDato = request.getParameter("eje");
                String tamano = request.getParameter("num");
                String mascara = request.getParameter("codClasifTram");
                String ob = request.getParameter("nombreCodTram");
                String orden = request.getParameter("codPlantilla");
                String descPlantilla = request.getParameter("nombDoc");
                String descTipoDato = request.getParameter("descTD");
                String rotulo = request.getParameter("rotulo"); 
                String visible = request.getParameter("visible");
                String oculto = request.getParameter("oculto");
                String bloqueado = request.getParameter("bloqueado");
                String plazoFecha = request.getParameter("plazoFecha");
                String checkPlazoFecha = request.getParameter("checkPlazoFecha");
                String validacion = request.getParameter("validacion");
                String operacion = request.getParameter("operacion");
                String agrupacionCampo = request.getParameter("agrupacionCampo");
                if (operacion == null)
                        operacion = new String("");

                defCampoVO.setCodCampo(codCampo);
                defCampoVO.setDescCampo(descCampo);
                defCampoVO.setCodPlantilla(codPlantilla);
                defCampoVO.setCodTipoDato(codTipoDato);
                defCampoVO.setTamano(tamano);
                defCampoVO.setDescMascara(mascara);
                defCampoVO.setObligat(ob);
                defCampoVO.setOrden(orden);
                defCampoVO.setDescPlantilla(descPlantilla);
                defCampoVO.setDescTipoDato(descTipoDato);
                defCampoVO.setRotulo(rotulo);
                defCampoVO.setVisible(visible);
                defCampoVO.setOculto(oculto);
                defCampoVO.setBloqueado(bloqueado);
                defCampoVO.setPlazoFecha(plazoFecha);
                defCampoVO.setCheckPlazoFecha(checkPlazoFecha);
                defCampoVO.setValidacion(validacion);
                defCampoVO.setOperacion(operacion);
                if(agrupacionCampo != null && !"".equalsIgnoreCase(agrupacionCampo) && !"undefined".equalsIgnoreCase(agrupacionCampo)){
                    defCampoVO.setCodAgrupacion(agrupacionCampo);
                }else{
                    defCampoVO.setCodAgrupacion("");
                }//if(agrupacionCampo != null && !"".equalsIgnoreCase(agrupacionCampo))
            }
            
            String codsAgrupacion = request.getParameter("codAgrupaciones");
            String descAgrupacion = request.getParameter("descAgrupaciones");
            String ordenAgrupacion = request.getParameter("ordenAgrupaciones");
            Vector listaAgrupaciones = new Vector();
            if(codsAgrupacion != null &&  !"".equals(codsAgrupacion) && !"undefined".equalsIgnoreCase(codsAgrupacion)){
                if(descAgrupacion != null &&  !"".equals(descAgrupacion) && !"undefined".equalsIgnoreCase(descAgrupacion)){
                    if(ordenAgrupacion != null &&  !"".equals(ordenAgrupacion) && !"undefined".equalsIgnoreCase(ordenAgrupacion)){
                        Vector listaCodsAgrupacion = listaTemasSeleccionados(codsAgrupacion);
                        Vector listaDescAgrupacion = listaTemasSeleccionados(descAgrupacion);
                        Vector listaOrdenAgrupacion = listaTemasSeleccionados(ordenAgrupacion);
                        for(int i = 0; i < listaCodsAgrupacion.size(); i++){
                            DefinicionAgrupacionCamposValueObject agrupacionCampo = new DefinicionAgrupacionCamposValueObject();
                                agrupacionCampo.setCodAgrupacion((String)listaCodsAgrupacion.get(i));
                                agrupacionCampo.setDescAgrupacion((String)listaDescAgrupacion.get(i));
                                agrupacionCampo.setOrdenAgrupacion(Integer.valueOf((String)listaOrdenAgrupacion.get(i)));
                                listaAgrupaciones.add(agrupacionCampo);
                        }//for(int i = 0; i < listaCodsAgrupacion.size(); i++)
                    }//if(ordenAgrupacion != null &&  !"".equals(ordenAgrupacion) && !"undefined".equalsIgnoreCase(ordenAgrupacion))
                }//if(descAgrupacion != null &&  !"".equals(descAgrupacion) && !"undefined".equalsIgnoreCase(descAgrupacion))
            }//if(codsAgrupacion != null &&  !"".equals(codsAgrupacion) && !"undefined".equalsIgnoreCase(codsAgrupacion))

            defCampoVO.setListaAgrupaciones(listaAgrupaciones);
            defCampoVO.setListaCamposDesplegables(DefinicionProcedimientosManager.getInstance().getListaCamposDesplegables(params));
            defCampoVO.setListaPlantillas(DefinicionProcedimientosManager.getInstance().getListaPlantillas(params));
            defCampoVO.setListaTipoDato(DefinicionProcedimientosManager.getInstance().getListaTipoDato(params));
            defCampoVO.setListaRelacionTipoDatoPlantillas(DefinicionProcedimientosManager.getInstance().getListaRelacionTipoDatoPlantillas(params));
            defCampoVO.setListaMascaras(DefinicionProcedimientosManager.getInstance().getListaMascaras(params));
            defCampoVO.setListaRelacionTipoDatoMascaras(DefinicionProcedimientosManager.getInstance().getListaRelacionTipoDatoMascaras(params));
            session.setAttribute("modoInicio",modoInicio);
            if(lectura != null && !lectura.equals("")) 
            {
                session.setAttribute("lectura",lectura);
            } 
            else 
            {
                session.setAttribute("lectura","no");
            } 
            defCampoForm.setDefinicionCampo(defCampoVO);

            opcion = "inicio";
      }else if (opcion.equals("VerOperacionNum")||opcion.equals("VerOperacionFec")||opcion.equals("VerValida")){
          try
          {
              //davidvim00 
              gVO.setAtributo("codMunicipio", request.getParameter("codMunicipio"));
              gVO.setAtributo("codProcedimiento", request.getParameter("codProcedimiento"));
              gVO.setAtributo("tipo_campo",request.getParameter("tipo_campo"));
              gVO.setAtributo("tramite",request.getParameter("tramite"));
              gVO.setAtributo("opcion_pr",request.getParameter("opcion_pr"));
              Vector aux = DatosSuplementariosDAO.getInstance().CargarCamposVer(params, gVO);
              request.setAttribute("listadoCampos",aux); 
          }catch (Exception ex) {
              ex.printStackTrace();
          }
       }else if (opcion.equals("VerExterno")){
          try
          {              
              String aux = DatosSuplementariosDAO.getInstance().CargarCamposExt(params); 
              response.setContentType("text/xml"); 
              PrintWriter out = response.getWriter();
              out.println(aux);
              out.flush();
              out.close();               
          }catch (Exception ex) {
              ex.printStackTrace();
      }
    
      }else if (opcion.equals("validarTamano")) {
          String codTipoDato = request.getParameter("codTipoDato");
          if (!codTipoDato.equals("3") && !codTipoDato.equals("4") && !codTipoDato.equals("5") && !codTipoDato.equals("6")) 
          {
              errors = defCampoForm.validate(mapping,request);
              if (!(errors.isEmpty())) {
                  saveErrors(request, errors);
                  return new ActionForward(mapping.getInput());
              }
          }                
      }else { // No hay usuario.
              m_Log.info("VerOperaciones --> no hay usuario");
                          opcion = "no_usuario";
      }
    }
      return (mapping.findForward(opcion));
}

private Vector listaTemasSeleccionados(String listTemasSelecc) {
  Vector lista = new Vector();
  StringTokenizer valores = null;
  if (listTemasSelecc != null) {
    valores = new StringTokenizer(listTemasSelecc,"зе",false);
    while (valores.hasMoreTokens()) {
      String valor = valores.nextToken();
      lista.addElement(valor);
    }
  }
  return lista;
}

}