  /* Generated by Together */
package es.altia.agora.interfaces.user.web.sge;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.sge.TablasIntercambiadorasValueObject;
import es.altia.agora.business.sge.DefinicionProcedimientosValueObject;
import es.altia.agora.business.sge.persistence.DefinicionTramitesManager;
import es.altia.agora.business.sge.persistence.DefinicionProcedimientosManager;
import es.altia.agora.business.sge.DefinicionTramitesValueObject;
import es.altia.agora.interfaces.user.web.helper.ActionHelper;
import es.altia.agora.interfaces.user.web.util.ActionSession;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;

import java.util.StringTokenizer;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

    public final class TablasIntercambiadorasAction extends ActionSession {

    protected static Log m_Log =
            LogFactory.getLog(TablasIntercambiadorasAction.class.getName());

        public ActionForward performSession(	ActionMapping mapping,
                    ActionForm form,
                    HttpServletRequest request,
                    HttpServletResponse response) throws IOException, ServletException {

      m_Log.debug("perform");
      ActionHelper myActionHelper = new ActionHelper(getLocale(request), getResources(request));


            // Validaremos los parametros del request especificados
      HttpSession session = request.getSession();
      String opcion ="";

      if ((session.getAttribute("usuario") != null)) {
        UsuarioValueObject usuario = (UsuarioValueObject)session.getAttribute("usuario");
        String[] params = usuario.getParamsCon();
        int cod_dep;
        int cod_uni;
        cod_dep= usuario.getDepCod();
        cod_uni= usuario.getUnidadOrgCod();

        // Si usuario en sesion es nulo --> error.

        ActionErrors errors = new ActionErrors();

        TablasIntercambiadorasForm tabInterForm = null;
        TablasIntercambiadorasValueObject tabInterVO= new TablasIntercambiadorasValueObject();
        TablasIntercambiadorasValueObject tabInterTramSSalVO= new TablasIntercambiadorasValueObject();
        TablasIntercambiadorasValueObject tabInterTramNSalVO= new TablasIntercambiadorasValueObject();

        if (form == null) {
          m_Log.debug("Rellenamos el form de Busqueda de Certificados");
          form = new TablasIntercambiadorasForm();
          if ("request".equals(mapping.getScope()))
            request.setAttribute(mapping.getAttribute(), form);
          else
            session.setAttribute(mapping.getAttribute(), form);
        }

        tabInterForm = (TablasIntercambiadorasForm)form;

        opcion = request.getParameter("opcion");
        if (m_Log.isInfoEnabled()) m_Log.info("la opcion en el action es " + opcion);
        String[] paramsDiputacion =	new String[7];
        tabInterForm.setTramitesCondSal(tabInterVO);
        tabInterForm.setTramitesSCondSal(tabInterTramSSalVO);
        tabInterForm.setTramitesNCondSal(tabInterTramNSalVO);


      if (opcion.equals("inicio")){
        Vector listaTramitesTodos = new Vector();
        String numeroCondicionSalida = request.getParameter("nCS");
        String codMun = request.getParameter("codMun");
        String codProc = request.getParameter("codProc");
        String codTram = request.getParameter("codTram");
        String listaCodTramFS = request.getParameter("eje");
        String listaDescTramFS = request.getParameter("num");
        String obligatorio = request.getParameter("codClasifTram");
        String listaNombreTramFS = request.getParameter("nombreCodTram");
        Vector listaCodTramitesFlujoSalida = listaTemasSeleccionados(listaCodTramFS);
        Vector listaDescTramitesFlujoSalida = listaTemasSeleccionados(listaDescTramFS);
        Vector listaNombreTramitesFlujoSalida = listaTemasSeleccionados(listaNombreTramFS);
        tabInterVO.setNumeroCondicionSalida(numeroCondicionSalida);
        tabInterVO.setCodMunicipio(codMun);
        tabInterVO.setCodProcedimiento(codProc);
        tabInterVO.setCodTramite(codTram);
        tabInterVO.setObligatorio(obligatorio);
        if(listaCodTramitesFlujoSalida.size() == 0) {
          tabInterVO = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaSeleccionada(tabInterVO,params);
        } else {
          Vector listaTramitesFlujoSalida = crearListaTramitesFlujoSalida(listaCodTramitesFlujoSalida,listaDescTramitesFlujoSalida,listaNombreTramitesFlujoSalida);
          tabInterVO.setListaTramitesSeleccion(listaTramitesFlujoSalida);
        }
        listaTramitesTodos = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaTodos(tabInterVO,params);
        tabInterVO.setListaTramitesTodos(listaTramitesTodos);

        tabInterForm.setTablasIntercambiadoras(tabInterVO);
        opcion = "inicio";
      } else if(opcion.equals("grabar")){
        tabInterVO = tabInterForm.getTablasIntercambiadoras();
        // Recuperar listas
        String listaCodTramitesFlujoSalida = request.getParameter("listaCodTramitesFlujoSalida");
        String listaNumerosSecuenciaFlujoSalida = request.getParameter("listaNumerosSecuenciaFlujoSalida");
        tabInterVO.setListaCodTramitesFlujoSalida(listaTemasSeleccionados(listaCodTramitesFlujoSalida));
        tabInterVO.setListaNumerosSecuenciaFlujoSalida(listaTemasSeleccionados(listaNumerosSecuenciaFlujoSalida));
        String obligatorio = request.getParameter("obligatorio");
        tabInterVO.setObligatorio(obligatorio);
        int i = DefinicionTramitesManager.getInstance().grabarFlujoSalida(tabInterVO,params);
        if(i == 0) {
          m_Log.debug("no grabado");
          opcion = "noGrabado";
        } else {
          m_Log.debug("grabado");
          opcion = "grabado";
        }
      } else if(opcion.equals("inicioListaSoloLectura")) {
        String numeroCondicionSalida = request.getParameter("nCS");
        String codMun = request.getParameter("codMun");
        String codProc = request.getParameter("codProc");
        String codTram = request.getParameter("codTram");
        tabInterVO.setNumeroCondicionSalida(numeroCondicionSalida);
        tabInterVO.setCodMunicipio(codMun);
        tabInterVO.setCodProcedimiento(codProc);
        tabInterVO.setCodTramite(codTram);
        String importar	= request.getParameter("codPlantilla");
      
        if("si".equals(importar)) {
            DefinicionProcedimientosValueObject defProcVO = new DefinicionProcedimientosValueObject();
            //defProcVO.setCodMunicipio("0");
            defProcVO.setCodMunicipio(codMun);
            String codAplicacion	= request.getParameter("nombDoc");
            if (m_Log.isDebugEnabled()) m_Log.debug("el codigo de la aplicacion es: " + codAplicacion);
            defProcVO.setCodAplicacion(codAplicacion);
          	String jndi =	DefinicionProcedimientosManager.getInstance().obtenerJndi(defProcVO,params);
            paramsDiputacion[0]	= params[0]; // "oracle";
            paramsDiputacion[6]	= jndi;
            params=paramsDiputacion;
        }

        tabInterVO = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaSeleccionada(tabInterVO,params);

        tabInterForm.setTablasIntercambiadoras(tabInterVO);
      }else if(opcion.equals("cargarListasTramSal")) {
        String nCSTramite = request.getParameter("nCSTramite");
        String nCSTramiteS = request.getParameter("nCSTramiteS");
        String nCSTramiteN = request.getParameter("nCSTramiteN");
        String codMun = request.getParameter("codMun");
        String codProc = request.getParameter("codProc");
        String codTram = request.getParameter("codTram");
        if (nCSTramite.equals("0")) {
            tabInterVO.setCodMunicipio(codMun);
            tabInterVO.setCodProcedimiento(codProc);
            tabInterVO.setCodTramite(codTram);
            tabInterVO.setNumeroCondicionSalida(nCSTramite);
            tabInterVO = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaSeleccionada(tabInterVO,params);
            tabInterForm.setTramitesCondSal(tabInterVO);
        } else {
            if (nCSTramiteS.equals("1")) {
                tabInterTramSSalVO.setCodMunicipio(codMun);
                tabInterTramSSalVO.setCodProcedimiento(codProc);
                tabInterTramSSalVO.setCodTramite(codTram);
                tabInterTramSSalVO.setNumeroCondicionSalida(nCSTramiteS);
                tabInterTramSSalVO = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaSeleccionada(tabInterTramSSalVO,params);
                tabInterForm.setTramitesSCondSal(tabInterTramSSalVO);
            }
            if (nCSTramiteN.equals("2")) {
                tabInterTramNSalVO.setCodMunicipio(codMun);
                tabInterTramNSalVO.setCodProcedimiento(codProc);
                tabInterTramNSalVO.setCodTramite(codTram);
                tabInterTramNSalVO.setNumeroCondicionSalida(nCSTramiteN);
                tabInterTramNSalVO = DefinicionTramitesManager.getInstance().getListaTramitesFlujoSalidaSeleccionada(tabInterTramNSalVO,params);
                tabInterForm.setTramitesNCondSal(tabInterTramNSalVO);
            }
        }
      }
   } else { // No hay usuario.
              m_Log.debug("TablasIntercambiadorasAction --> no hay usuario");
              opcion = "no_usuario";
   }

    /* Redirigimos al JSP de salida*/
        return (mapping.findForward(opcion));

  }
  private Vector listaTemasSeleccionados(String listSelecc) {
    Vector lista = new Vector();
    StringTokenizer codigos = null;

    if (listSelecc != null) {
      codigos = new StringTokenizer(listSelecc,"зе,",false);

      while (codigos.hasMoreTokens()) {
        String cod = codigos.nextToken();
        lista.addElement(cod);
      }

    }
    return lista;
  }

  private Vector crearListaTramitesFlujoSalida(Vector listaCodTramitesFlujoSalida,Vector listaDescTramitesFlujoSalida,
      Vector listaNombreTramitesFlujoSalida) {
    Vector listaTramitesFlujoSalida = new Vector();
    for(int i=0;i<listaCodTramitesFlujoSalida.size();i++) {
      DefinicionTramitesValueObject t = new DefinicionTramitesValueObject();
      t.setIdTramiteFlujoSalida((String)listaCodTramitesFlujoSalida.elementAt(i));
      t.setCodTramiteFlujoSalida((String)listaNombreTramitesFlujoSalida.elementAt(i));
      t.setNombreTramiteFlujoSalida((String)listaDescTramitesFlujoSalida.elementAt(i));
      listaTramitesFlujoSalida.addElement(t);
    }
    return listaTramitesFlujoSalida;
  }
}