/* Generated by Together */

package es.altia.agora.interfaces.user.web.util;

import es.altia.agora.interfaces.user.web.portafirmas.SessionManager;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


public final class SalirAppAction extends ActionSession{
    protected static Log m_Log = LogFactory.getLog(SalirAppAction.class.getName());

    public ActionForward performSession(	ActionMapping mapping, 
											ActionForm form, 
											HttpServletRequest request, 
											HttpServletResponse response)
		throws IOException, ServletException {

		 HttpSession session = request.getSession();
            
		String app = request.getParameter("1");	
		if ("1".equals(app)){
			if(session.getAttribute("usuario") != null)
			   session.removeAttribute("usuario");
			if(session.getAttribute("registroUsuario") != null)
			   session.removeAttribute("registroUsuario");		
		}
        
        String codApp = request.getParameter("app");
        // Acciones al cerrar el portafirmas.
        if ("11".equals(codApp)) SessionManager.removeSelectedIndex(request);

        m_Log.debug("Fin sesion");
		return mapping.findForward("salir");			
	}
}
