/* Generated by Together */

package es.altia.agora.interfaces.user.web.util;

import es.altia.agora.business.select.*;

import java.util.Vector;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class SelectBean {

    protected static Log m_log = LogFactory.getLog(SelectBean.class.getName());
    
    public SelectBean(){
        this.selectValue=new SelectValueObject();
    }
    /** Construye una nueva Select que devuelve una única descripcion, y cuyo estado esta definido en los parametros */
    public SelectBean(String col_cod, String col_desc_c, String nom_tabla, String col_where, String valor_where, String col_where2, String valor_where2) {
            this.selectValue=new SelectValueObject(col_cod,col_desc_c,nom_tabla,col_where,valor_where,col_where2,valor_where2);
    }

    /** Construye una nueva Select que devuelve las descripciones en 2 idiomas, y cuyo estado esta definido en los parametros */
    public SelectBean(String col_cod, String col_desc_c, String col_desc_e, String nom_tabla, String col_where, String valor_where, String col_where2, String valor_where2) {
            this.selectValue=new SelectValueObject(col_cod,col_desc_c,col_desc_e,nom_tabla,col_where,valor_where,col_where2,valor_where2);
    }

    public String getNombreTabla(){return this.selectValue.getNom_tabla();}
    public void setNombreTabla(String param){this.selectValue.setNom_tabla(param);}

    public String getNombreCampoCodigo(){return this.selectValue.getCol_cod();}
    public void setNombreCampoCodigo(String param){this.selectValue.setCol_cod(param);}

    public String getNombreCampoDescripcionCast(){return this.selectValue.getCol_desc_c();}
    public void setNombreCampoDescripcionCast(String param){this.selectValue.setCol_desc_c(param);}

    public String getNombreCampoDescripcionEusk(){return this.selectValue.getCol_desc_e();}
    public void setNombreCampoDescripcionEusk(String param){this.selectValue.setCol_desc_e(param);}

    public String getNombreCampoWhere(){return this.selectValue.getCol_where();}
    public void setNombreCampoWhere(String param){this.selectValue.setCol_where(param);}

    public String getValorCampoWhere(){return this.selectValue.getValor_where();}
    public void setValorCampoWhere(String param){this.selectValue.setValor_where(param);}

    public String getNombreCampoWhere2(){return this.selectValue.getCol_where2();}
    public void setNombreCampoWhere2(String param){this.selectValue.setCol_where2(param);}

    public String getValorCampoWhere2(){return this.selectValue.getValor_where2();}
    public void setValorCampoWhere2(String param){this.selectValue.setValor_where2(param);}


    public String getDescripcion(){
        String aux=null;
           try{
                //SelectServicesRemote remote = BeanHelper.getSelectServices();
                //aux=remote.getSelectValue(this.selectValue).getValor_desc();
                if(m_log.isDebugEnabled()) m_log.debug("Obteniendo descripcion................ "+aux);
           }
            catch (Exception se) {
               se.printStackTrace();
           }
           return aux;
    }


    public Vector getLista(){
           try{
                //SelectServicesRemote remote = BeanHelper.getSelectServices();
                //return remote.getSelectValue(this.selectValue).getLista_resultado();
           }
            catch (Exception se) {
               se.printStackTrace();
           }
           return null;
    }



    private SelectValueObject selectValue=null;

   /* private String nombreTabla=null;
    private String nombreCampoCodigo=null;
    private String nombreCampoDescripcionCast=null;
    private String nombreCampoDescripcionEusk=null;
    private String nombreCampoWhere=null;
    private String valorCampoWhere=null;*/
}
